### ISSUE TITLE
String class that automatically cats?

### ISSUE THREAD

**Issue by hadley** [tidyverse/glue#10]
```
cat_string <- function(x) {
  stopifnot(is.character(x))
  
  structure(x, class = "cat_string")
}

print.cat_string <- function(x, ..., sep = "\n") {
  cat(x, ..., sep = sep)
}
```

**Comment by jimhester** [comment]
So would the idea be that fstrings (or whatever we call this package) always produces strings of this class?

**Comment by hadley** [comment]
I'm not sure. Probably not, but it would be another useful helper

**Comment by jimhester** [comment]
I ended up making the functions do this by default and added a `as.character()` method to down class to a bare character vector.
