### ISSUE TITLE
Bullets and comma lists

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/glue#104]
In _tibble_ we have:

``` r
tibble:::commas(letters)
#> [1] "a, b, c, d, e, … (and 21 more)"
glue::as_glue(tibble:::bullets("header", letters))
#> header
#> * a
#> * b
#> * c
#> * d
#> * e
#> * … and 21 more problems
```

> Created on 2018-08-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I wonder if some or all of this should live in _glue_ instead.

**Comment by jimhester** [comment]
`glue_collapse()` supports some of this already.

```r
glue::glue_collapse(letters, ", ", width = 20)
#> a, b, c, d, e, f,...
glue::glue_collapse(c("header", letters), "\n* ")
#> header
#> * a
#> * b
#> * c
#> * d
#> * e
#> * f
#> * g
#> * h
#> * i
#> * j
#> * k
#> * l
#> * m
#> * n
#> * o
#> * p
#> * q
#> * r
#> * s
#> * t
#> * u
#> * v
#> * w
#> * x
#> * y
#> * z
```

Seems like it could get the rest of the way by having it a argument for number of items and the trailing message.

**Comment by krlmlr** [comment]
Is there room for higher-level functions like `bullets()` and `commas()` ? I like the idea of limiting the total width too.

**Comment by jennybc** [comment]
I think at this point, cli is where to turn for this sort of functionality (bullets are under development there, for example).
