### ISSUE TITLE
Should glue strings print with a header?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/glue#106]
Perhaps glue strings should print with a header so they are not confused with code:

```r
foo <- "x"
bar <- "y"
glue::glue("{foo} ~ {bar}")
#> x ~ y

x ~ y
#> x ~ y
```

With the header it'd look like:

```r
glue::glue("{foo} ~ {bar}")
#> <glue>
#> x ~ y
```

Another solution is to keep R's string representation, which would be more consistent with base strings. The downside is that the output would be heavier when the string contains formatting characters:

```r
glue("x ~ y")
#> <glue>
#> "x ~ y"

glue("x\ny")
#> <glue>
#> "x\ny"
#> -- Output --
#> x
#> y
```

**Comment by jimhester** [comment]
I think I prefer the printing as-is, but I appreciate the isuse.
