### ISSUE TITLE
NULL, NA, and empty character vectors are unexpectedly converted when in list

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/glue#110]
I'm not sure how glue is supposed to handle a list, but I feel this is inconsistent.

``` r
glue::glue("{x}", x = NULL)

glue::glue("{x}", x = NA)
#> NA

glue::glue("{x}", x = character(0))

x <- list("a", NULL, NA, character(0))
glue::glue("{x}")
#> a
#> NULL
#> NA
#> character(0)
```

<sup>Created on 2018-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Thanks. So, is this expected...?

**Comment by jimhester** [comment]
Yeah it is expected, lists are implicitly converted to characters by both `paste()` and `sprintf()` and right now we don't treat them any differently in `glue()`.

**Comment by yutannihilation** [comment]
OK. I rather feel it's good if we have control over how missing or empty elements are translated just as we do with `.na` for atomic vectors, but I don't have strong opinion here (yet). Thanks for the explanation, anyway 👍
