### ISSUE TITLE
FR: Simple syntax for single variable interpolation

### ISSUE THREAD

**Issue by ctbrown** [tidyverse/glue#111]
I use this all the time when I am piping around strings such as filename.  I thought that you might consider for `glue` package where I think it fits well.

```r
#' @param . single value coerceed to a character 
#' 
#' @details 
#' 
#' `glue_this` is a short-cut for piping a single value into `...` expressions. 
#' The single value is assigned to `.` and can be interpolated in the expression(s)
#' using `{.}`  
#' 
#' @examples 
#' 
#'   "Fred" %>% glue_this('This is {.}; Say "Hi" to {.}!')   # This is Fred; Say "Hi" to Fred!     
#'   
#' @export   
  
glue_this <- function( ., ..., .open = "{", .close = "}" ) { 
  env <- as.environment( list(. = .) )
  glue::glue( ..., .envir=as.environment( list( . = as.character(.) )), .open=.open, .close=.close )
}
  
```

I am happy to add this as a PR with tests, etc. If you are interested.

**Comment by jimhester** [comment]
Thanks you for the suggestion, however I think I would just do this instead

``` r
library(magrittr)
library(glue)
"Fred" %>% glue('This is {.}; Say "Hi" to {.}', `.` = .)
#> This is Fred; Say "Hi" to Fred
```

Or even give the argument a more informative name to make it more self-documenting, one of the primary goals of glue.

```r
"Fred" %>% glue('This is {name}; Say "Hi" to {name}', name = .)
#> This is Fred; Say "Hi" to Fred
```

<sup>Created on 2018-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ctbrown** [comment]
Oh ... total makes sense.  I am dense.  Please close.
