### ISSUE TITLE
Minor website issues

### ISSUE THREAD

**Issue by hadley** [tidyverse/glue#119]
* [ ] README needs a h2: we usually do `## Overview` (otherwise the padding at the top of the homepage isn't correct)

* [ ] Should use retina logo (i.e. `use_logo()` + https://github.com/rstudio/hex-stickers)

* [ ] Need favicons (i.e. `pkgdown::build_favicon()`)

**Comment by cdhowe** [comment]
I'll take this one as a way to learn how to properly do a pull request in the tidyverse world -- I'm at the front table for pull request newbies.
