### ISSUE TITLE
Escape newlines

### ISSUE THREAD

**Issue by lionel-** [tidyverse/glue#12]
Would it make sense for

```r
glue::glue("foo bar \
            baz")
```

to be equivalent to

```r
glue::glue("foo bar baz")
```

so long messages can be broken down in several lines in the code?

**Comment by jimhester** [comment]
I think the problem there is the R parser does not differentiate between a `\` and the end of the line and no `\` at all.

``` r
"foo bar \
baz"
#> [1] "foo bar \nbaz"
"foo bar 
baz"
#> [1] "foo bar \nbaz"
"foo bar \nbaz"
#> [1] "foo bar \nbaz"
```
We could maybe support `\\` before a newline swallowing the newline?

**Comment by lionel-** [comment]
This would slightly improve the looks of message functions:

```r
  warn(glue(
    "the underscored versions are deprecated in favour of ",
    "tidy evaluation idioms. Please see unquoting documentation ",
    "in rlang."
  ))
```

versus

```r
  warn(glue(
    "the underscored versions are deprecated in favour of \\
     tidy evaluation idioms. Please see unquoting documentation \\
     in rlang."
  ))
```

But that's not really important if hard to implement.

**Comment by jimhester** [comment]
Not hard, this should now be done, thanks for the suggestion!

**Comment by lionel-** [comment]
that was quick :)

**Comment by hadley** [comment]
Isn't that going to lead to weird leading whitespace?

**Comment by lionel-** [comment]
As far as I can tell the leading whitespace is correctly removed.

**Comment by jimhester** [comment]
Yeah I remove the newlines after removing whitespace, so it seems to do what you would want there.

**Comment by hadley** [comment]
Which causes a different set of problems if you want to selectively indent the lines, but it's probably the right tradeoff for here.
