### ISSUE TITLE
How to type curly bracket { in the glue content

### ISSUE THREAD

**Issue by JiaxiangBU** [tidyverse/glue#127]
``` r
library(glue)
glue("@online{Li2019,")
#> Error in glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open, : Expecting '}'
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by JiaxiangBU** [comment]
Temporally, 

``` r
library(glue)
library(rebus)
library(tidyverse)
open <- '{'
glue("@online{open}Li2019,") %>% 
    cat
#> @online{Li2019,
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I don't think it is an effcient way.

**Comment by yutannihilation** [comment]
You can change the opening delimiter by `.open`.

``` r
glue::glue("@online{Li2019,", .open = "{{")
#> @online{Li2019,
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by JiaxiangBU** [comment]
@yutannihilation Hi, thanks for your quick reply. It works for me by customing the open and close delimiters.

``` r
add_text <- 123
glue::glue("@online{Li2019,", .open = "{{")
#> @online{Li2019,
glue::glue("@online{Li20190{{add_text}},", .open = "{{")
#> @online{Li20190123},
glue::glue("@online{Li2019-{add_text},", .open = "{{")
#> @online{Li2019-{add_text},
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by 10b14224cc** [comment]
For the closing delimiter use `.close`
