### ISSUE TITLE
Consider adding `-` method as new feature

### ISSUE THREAD

**Issue by stufield** [tidyverse/glue#129]
There is a `+` method for `glue` objects, how about a `-` method also which is essentially a `x not in y`? Something like this ...

```r
`-.glue` <- function(e1, e2) {
  e1[!e1 %in% e2]
}
shop <- as_glue(c("milk", "eggs", "bread"))
shop - "eggs"
shop - c("eggs", "hotdogs")    # same
```

No pattern matching of course. Logically it would "read" as ... "give me the `shop` list minus the `eggs`".

Happy to submit a PR if you like!

**Comment by jimhester** [comment]
I think what `+` does with strings is pretty unambiguous, but it is not clear what `-` would do. Should it do what you describe, or should it remove the characters from the end of strings and then be the inverse of the `+` e.g. 

```r
shop - "s"
#> c("milk", "egg", "bread")`
```

Because of this uncertainty I think it best not to implement `-`.
