### ISSUE TITLE
Optional flag to prevent leading/trailing newline stripping?

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/glue#131]
I really enjoy using `glue`, but at times I have strings already in a very specific format/template, and that may include a trailing (or leading) newline character. I also completely understand the rationale behind the newline-stripping behavior, but I'm wondering if it'd be useful to have an optional flag to turn that behavior off for particular situations?

**Comment by jimhester** [comment]
That is what the `.trim` argument is for.
