### ISSUE TITLE
glue::single_quote does not handle NA

### ISSUE THREAD

**Issue by colearendt** [tidyverse/glue#135]
`glue::glue()` has a `.na` parameter that allows you to control how `NA` is treated.

I would argue that `glue::single_quote(NA)` should be `NA` or should at least be controllable. Honestly, in the use cases I was trying (generating SQL), either `single_quote(NA) = NA` or `single_quote(NA) = ''` made the most sense to me. `"NA"` feels weird in that it is neither single quoted nor a value consistent with the nature of NA.

``` r
var <- NA
glue::single_quote(glue::glue("hello {NA}", .na = ""))
#> [1] "'hello '"
glue::single_quote(glue::glue("hello {var}", .na = ""))
#> [1] "'hello '"

# my confusion rests here
glue::single_quote(NA)
#> [1] "NA"

glue::single_quote(NULL)
#> character(0)
```

<sup>Created on 2019-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
If you were generating SQL why were you not using `glue_sql()`?

But anyway I agree the behavior is not correct, will fix it so these all return a `NA` value.

**Comment by colearendt** [comment]
Awesome, thanks! I don't really remember, to be honest 😬 I think I had a FR for `glue_sql`, but this is all I recorded. Next time I work on this project, I will definitely let you know if there is something other than ignorance of functionality that kept me from using `glue_sql` 😄
