### ISSUE TITLE
Unnamed arguments of length > 1

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/glue#14]
``` r
glue::glue("{1:3}")
#> 1
#> 2
#> 3
glue::glue(1:3)
#> Error: All unnamed arguments must be length 1
```

Can the two expressions be made equivalent? This will simplify the transition from `paste0()`.

**Comment by jimhester** [comment]
I don't think so, the problem is if you support `1:3` you also implicitly support `c("1", "2", "3")`, and implicitly support nested expansions `c("{1:3}", "{4:6}", "{7:9}")`. Supporting the latter would make the implementation much more complicated and confusing to debug.

**Comment by krlmlr** [comment]
I see. Perhaps if we had a dedicated `.format` argument (that can also be `NULL`), and performed brace expansions only for that argument?
