### ISSUE TITLE
Add vctrs definitions

### ISSUE THREAD

**Issue by hadley** [tidyverse/glue#142]
e.g. https://github.com/tidyverse/tidyr/issues/676

``` r
library(vctrs)
library(glue)

x <- glue("abc")
vec_c(x, x)
#> Only bare vectors have shapes.
```

<sup>Created on 2019-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
It seems strange to me that vctrs doesn't handle this automatically if a class inherits from a base vector...

**Comment by hadley** [comment]
I also filed an issue about that — https://github.com/r-lib/vctrs/issues/497.

But even when that's fixed, I think you need to decide what `vec_c(glue("x"), "y")` should return.

**Comment by jimhester** [comment]
Should be fixed by https://github.com/tidyverse/glue/pull/172
