### ISSUE TITLE
Evaluate a nested template

### ISSUE THREAD

**Issue by grepinsight** [tidyverse/glue#143]
# Issue

If I use a glue template within another glue template, then I get the raw template instead of the evaluation of the template. I can currently work around the issue by using the third approach described below, but it would be nice if evaluation happens recursively

# Reprex 

``` r
library(tidyverse)
template <- "{my_var}.txt"
df <- tribble(~my_var, 
        "a",
        "b",
        "c")
df %>% 
  mutate(file=glue::glue(template))
#> # A tibble: 3 x 2
#>   my_var file  
#>   <chr>  <glue>
#> 1 a      a.txt 
#> 2 b      b.txt 
#> 3 c      c.txt

df %>% 
  mutate(file=glue::glue("touch {template}"))
#> # A tibble: 3 x 2
#>   my_var file              
#>   <chr>  <glue>            
#> 1 a      touch {my_var}.txt
#> 2 b      touch {my_var}.txt
#> 3 c      touch {my_var}.txt

df %>% 
  mutate(file=glue::glue("touch {glue::glue(template)}"))
#> # A tibble: 3 x 2
#>   my_var file       
#>   <chr>  <glue>     
#> 1 a      touch a.txt
#> 2 b      touch b.txt
#> 3 c      touch c.txt
```

<sup>Created on 2019-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jcheng5** [comment]
Recursive evaluation is _extremely_ dangerous, and makes it impossible to use `glue` on arbitrary values--I recommend this not even be added as an optional feature.

If you have some very narrow use case where you have carefully validated all your inputs, and you MUST have recursive execution, I recommend just calling `glue::glue` in a loop until it stops changing (and fail if you reach some large number of iterations without stabilizing).

**Comment by grepinsight** [comment]
Thanks for the insight @jcheng5 ! If you feel strongly against that, I have no doubt you're right.

In order for me to better understand this, can you provide me with one minimal example that illustrate your point? I.e. what can terribly go wrong?

**Comment by jcheng5** [comment]
Sure!

```r
df <- read.csv("data.csv")
glue::glue_data(df, "{first_name} {last_name}")
```

Imagine the data.csv originates from, say, a web signup form.

With today's `glue()` behavior, this code will work as long as `df` has the correct shape (i.e. contains `first_name` and `last_name` columns).

With recursive evaluation, this code is now a CVSS Level 10 vulnerability! A user of the web form can simply say that their first name is `{system("#rm -rf ~")}` (I've added a `#` for safety purposes, but imagine it without) and your week is ruined.

Using glue with untrusted data is tricky to do right, but with recursive execution it goes from "tricky" to "impossible". The underlying security principle here is that you must always be clear on what values represent **code** and what values represent **data**; it's OK for untrusted values to be data, **it's NEVER OK for them to be code**. Recursive evaluation erases this important boundary by always treating the resulting data as code!

**Comment by jcheng5** [comment]
By the way, this is equally unsafe:

```r
df <- read.csv("data.csv")
fullname <- glue::glue_data(df, "{first_name} {last_name}")
glue::glue_data(df, paste0(fullname, ": {status}"))
```

While this is (AFAICT) safe:

```r
df <- read.csv("data.csv")
fullname <- glue::glue_data(df, "{first_name} {last_name}")
glue::glue_data(df, "{fullname}: {status}")
```

Again, it's OK for untrusted values to be data, it's never OK for them to be code; and glue patterns are code! In my code reviews, I've started rejecting pull requests that contain `glue()` calls where the pattern is not a string literal. It's just too dangerous to do otherwise.

**Comment by grepinsight** [comment]
I now see. Thank you for the illustrative examples and the guideline 👍

> The underlying security principle here is that you must always be clear on what values represent code and what values represent data; it's OK for untrusted values to be data, it's NEVER OK for them to be code. Recursive evaluation erases this important boundary by always treating the resulting data as code!

**Comment by jimhester** [comment]
@jcheng5 for your use case you might want to define a stricter version of glue, that does not do arbitrary evaluation and only looks up symbols from an environment. e.g.

``` r
get_transformer <- function(text, envir) {
  get(text, envir = envir)
}

glue_data_safe <- function(..., .envir = parent.frame()) {
  glue::glue_data(..., .transformer = get_transformer, .envir = .envir)
}

glue_safe <- function(..., .envir = parent.frame()) {
  glue_data_safe(.x = NULL, ..., .envir = .envir)
}

glue_data_safe(head(mtcars), "hp = {hp}")
#> hp = 110
#> hp = 110
#> hp = 93
#> hp = 110
#> hp = 175
#> hp = 105
glue_data_safe(head(mtcars), "hp = {hp + 1}")
#> Error in get(text, envir = envir): object 'hp + 1' not found
```

<sup>Created on 2020-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@grepinsight if you want this recursive behavior again you can define a transformer that gives it to you.

``` r
recursive_transformer <- function(text, envir) {
  glue::glue(glue::identity_transformer(text, envir), .envir = envir)
}

library(dplyr)
template <- "{my_var}.txt"
df <- tribble(~my_var, 
        "a",
        "b",
        "c")
df %>% 
  mutate(file=glue::glue(template))
#> # A tibble: 3 x 2
#>   my_var file  
#>   <chr>  <glue>
#> 1 a      a.txt 
#> 2 b      b.txt 
#> 3 c      c.txt

df %>% 
  mutate(file=glue::glue("touch {template}", .transformer = recursive_transformer))
#> # A tibble: 3 x 2
#>   my_var file       
#>   <chr>  <glue>     
#> 1 a      touch a.txt
#> 2 b      touch b.txt
#> 3 c      touch c.txt
```

<sup>Created on 2020-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
