### ISSUE TITLE
backslashes need to be re-doubled

### ISSUE THREAD

**Issue by r2evans** [tidyverse/glue#147]
The docs do say:

> Backslashes do need to be doubled just like in all R strings

but I find that they need to be doubled again beyond what R strings normally require.

```r
cat("hello\n")
# hello
cat("hello\\n")
# hello\n
glue('{cat("hello\n")}')
# hello
                              # <-- empty line
glue('{cat("hello\\n")}')
# hello
                              # <-- empty line
cat("hello\\\\n")
# hello\\n
glue('{cat("hello\\\\n")}')
# hello\n
```

Better example that causes an error:

```r
mystr <- "quux1"
gsub('\\D', '', mystr)
# [1] "1"
glue("{gsub('\\D', '', mystr)}")
# Error: '\D' is an unrecognized escape in character string starting "'\D"
glue("{gsub('\\\\D', '', mystr)}")
# 1
```

I find the example for *"backslashes do need to be doubled"* to be a bit difficult to read and interpret, so perhaps I'm misunderstanding:

```
  `foo}\`` <- "foo"
glue("{
      {
        '}\\'' # { and } in comments, single quotes
        \"}\\\"\" # or double quotes are ignored
        `foo}\\`` # as are { in backticks
      }
  }")
#> foo
```

---

R-3.5.3, glue-1.3.1

**Comment by cderv** [comment]
This comes from the default `identy_transformer` behavior, which is a wrapper around `eval(parse())` R base functions.

``` r
mystr <- "quux1"
glue::identity_transformer('gsub("\\D", "", mystr)', globalenv())
#> Error: '\D' is an unrecognized escape in character string starting ""\D"
glue::identity_transformer('gsub("\\\\D", "", mystr)', globalenv())
#> [1] "1"
parse(text = 'gsub("\\D", "", mystr)', keep.source = FALSE)
#> Error: '\D' is an unrecognized escape in character string starting ""\D"
```

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think the double escape is required even without glue: 
* One for escaping in the REGEX pattern for gsub
* Second for escaping in R parsing to get an expression from a string (with `parse`)

Just wanted to add these precisions. Hope it helps explain the behavior

**Comment by jimhester** [comment]
The only way to tell the R parser you want a backslash is `\\`, as the R parser uses backslash as the escape character. So a double backslash is `\\\\`. The example you mention is meant to show that braces can be escaped in all the ways possible by R, not to illustrate the use of backslashes. 

The comment is just mentioning that backslashes work the same way as a normal R string.

**Comment by r2evans** [comment]
@cderv's comment provided the necessary context, thanks all.
