### ISSUE TITLE
Surprising behaviour with empty vectors

### ISSUE THREAD

**Issue by csgillespie** [tidyverse/glue#148]
The following doesn't produce any output
```
x = integer(0)
glue::glue("a{x}")
```
---

This can lead to surprising behaviour:
```
library("glue")
b = 1
glue("a{b[TRUE]}")
# a1
paste0("a", b[TRUE])
# [1] "a1"
```
But when I the vector returns integer(0), this is unexpected
```
# The` a` disappears
glue("a{b[FALSE]}")

paste0("a", b[FALSE])
#[1] "a"
```

---
```
> packageVersion("glue")
[1] '1.3.1'
```

**Comment by jimhester** [comment]
This is expected, 0 length inputs produce 0 length outputs. Consistency with paste0 is in general not a goal of glue.

**Comment by csgillespie** [comment]
I only used `paste0()` as an example/sanity check. 

This still seems strange to me. For example,
```
glue("test{'s'[TRUE]}")
glue("test{'s'[FALSE]}")
```
would surprise most people. Is this behaviour documented?

**Comment by kent37** [comment]
This surprised me also. Yes, 0 length inputs produce 0 length outputs, but when there are non-zero-length items in the glue string, they should be included in the output. Here is a motivating example -- a simple function to pretty-print a list.
``` r
library(glue)
library(purrr)

# Pretty print a list
pretty_list = function(l) {
  items = purrr::imap_chr(l, function(item, name) {
    glue('{name}: {item}')
  })
  paste(items, collapse='\n')
}

# Works
cat(pretty_list(list(foo='bar', baz='bop')))
#> foo: bar
#> baz: bop

# Fails
cat(pretty_list(list(foo='bar', baz=NULL)))
#> Error: Result 2 must be a single string, not a vector of class `glue/character` and of length 0
```

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
There are a number of issues discussing this, so I am going to close this one.
