### ISSUE TITLE
`glue_sql` should not quote `ident_q`

### ISSUE THREAD

**Issue by antoine-sachet** [tidyverse/glue#149]
Using ``{`...`} `` in `glue_sql` escapes an identifier such as a db name or table name. 

However, it should leave already quoted identifiers (`ident_q`) untouched. In particular, `in_schema("db", "tbl")` should not become `"db.tbl"` (assuming ANSI quotes).

``` r
tbl <- dbplyr::in_schema("mydb", "mytbl")
               glue::glue_sql('SELECT * from {`tbl`}', .con = DBI::ANSI())
#> <SQL> SELECT * from "mydb.mytbl"
```

<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Instead, I would have expected `glue_sql` respect the `ident_q` and generate:

```
#> <SQL> SELECT * from mydb.mytbl
```

Of course, ideally what we would _actually_ want is `"mydb"."mytbl"` but I guess this is [a problem for `dbplyr::in_schema`](https://github.com/tidyverse/dbplyr/issues/287) (after all, you would expect an ident_**q** object to be quoted...).

**Comment by jimhester** [comment]
I think this is just a problem with **dbplyr**, if you construct the ID using a `DBI::Id()` this will work properly.

``` r
tbl <- DBI::Id(schema = "mydb", table = "mytbl")
glue::glue_sql('SELECT * from {`tbl`}', .con = DBI::ANSI())
#> <SQL> SELECT * from "mydb"."mytbl"
```

<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
