### ISSUE TITLE
Expose .transformer argument in glue_[data_]sql() and export sql_quote_transformer

### ISSUE THREAD

**Issue by pnacht** [tidyverse/glue#154]
Is there a particular reason why the `.transformer()` argument isn't made available in `glue_sql` and `glue_data_sql`?

I was hoping to create my own transformer to compose with `sql_quote_transformer` which adds a suffix `-` (i.e. `{foo-}`) which indicates the contents of `foo` should be evaluated raw, without escaping.

This can be very unsafe, of course, but it'd sometimes be useful when dynamically building the SQL string from safe chunks.

I currently do this by wrapping the relevant strings with `DBI::SQL`, which works fine, but having a raw transformer with the `{foo-}` shorthand would be nice.

However, since the .transformer argument isn't exposed, this can't be done. And, actually, even if it were exposed, I wouldn't be able to compose my transformer with the `sql_quote_transformer` because it currently isn't exported.

So the only way I could do this would be by copying the current implementation of `glue_sql` and the `sql_quote_transformer` and hope they're never modified.

So, is there a reason why the `.transformer` isn't exposed and/or why the `sql_quote_transformer` isn't exported? The other solution would be doing the transformer composition internally, but I wouldn't know how to do that without adding a dependency to `purrr::compose`, which goes against the "small, fast, dependency free" philosophy of `glue`.

**Comment by jimhester** [comment]
Well because `glue_sql()` already use the `.transformer` argument, we can't really expose it. If you want a customized version of `glue_sql()` I would suggest you just copy the code from the `sql_quote_transformer`, modify it as you need to and create your own personal version of `glue_sql()`.

**Comment by pnacht** [comment]
But couldn't it be exposed in the same manner as `.envir` and `.na`, as an argument with a default value?
