### ISSUE TITLE
Using named arguments at `...`

### ISSUE THREAD

**Issue by llrs** [tidyverse/glue#156]
I tried to use the dots in a function and then use the named arguments in glue but I couldn't make it work. 

Perhaps this is related to #137 but I couldn't find if it is possible or not. 

``` r
library("glue")
f <- function(...) {
    print(glue("{a} + {b}"))
    sum(...)
}
f(a = 2, b = 3)
#> Error in eval(parse(text = text, keep.source = FALSE), envir): object 'a' not found
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I tried some variations with setting other environments but I didn't manage to make it work. Is this behaviour considered for glue?

**Comment by jimhester** [comment]
You have to pass the `...` to the glue call as well, e.g.

``` r
library("glue")
f <- function(...) {
    print(glue("{a} + {b}", ...))
    sum(...)
}
f(a = 2, b = 3)
#> 2 + 3
#> [1] 5
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by llrs** [comment]
Oh, sorry. Thanks!

**Comment by artemklevtsov** [comment]
But you can't nested call.

```r
library("glue")
g <- function(...) {
  f(...)
}
f <- function(...) {
  print(glue("{a} + {b}"))
  sum(...)
}
g(a = 2, b = 3)
# Error in eval(parse(text = text, keep.source = FALSE), envir) : 
#  object 'a' not found
```

**Comment by yutannihilation** [comment]
You have to pass the `...` to the glue call, in case you want someone to repeat this for you :)
