### ISSUE TITLE
Empty template {} returns character(0) output

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/glue#157]
Is the behavior below expected?
I ran into a unique situation recently where the template _itself_ has an empty splice region (`{}`), leading to an empty vector as a result:
```R
str(glue::glue("{}{1+1}"))
#>  'glue' chr(0)
```
In the above example, I _think_(?) most would expect something like this as output:
```R
str(glue::glue("{1+1}"))
#>  'glue' chr "2"
```
... but perhaps this is intentional?

**Comment by jimhester** [comment]
Yes it is intentional, `{}` produces `NULL`, and the principle glue follows is 0 length inputs should generate 0 length outputs.

see https://github.com/tidyverse/glue/issues/100, https://github.com/tidyverse/glue/issues/84 for additional issues related to this.
