### ISSUE TITLE
Mixing glue with "character" class

### ISSUE THREAD

**Issue by isteves** [tidyverse/glue#160]
I love how readable `glue()` code is, but I refrain from using it in two cases: (a) when I want to minimize dependencies and (b) when mixed with regular "character"s.  

A [previous issue](https://github.com/tidyverse/dplyr/issues/3478) touched on (b), and I was hoping it could be revisited.  

``` r
library(dplyr)
library(glue)

x <- "bar"

case_when(
  x == "foo" ~ "x is foo",
  TRUE ~ sprintf("x is %s!", x)
)
#> [1] "x is bar!"

case_when(
  x == "foo" ~ "x is foo",
  TRUE ~ glue("x is {x}!")
)
#> must have class `character`, not class `glue/character`

case_when(
  x == "foo" ~ glue("x is foo"),
  TRUE ~ glue("x is {x}!")
)
#> x is bar!
```

<sup>Created on 2019-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I would love for the middle case to work, especially since `glue()` _seems_ like it should be compatible with the outputs of `paste()` and `sprintf()`, and with character types in general.  I can think of two possible solutions:

* loosen the requirements in `dplyr:::check_class()` (specifically: `identical(class(x), class(template))`) to match any classes
* create a version of glue that outputs type "character" only

Thoughts?  Happy to contribute to the change if it helps!

**Comment by yutannihilation** [comment]
I guess this should be fixed when `case_when()` is rewritten with vctrs-integration. The corresponding issue was probably https://github.com/tidyverse/dplyr/issues/4389, but it seems now tracked in https://github.com/r-lib/funs/issues/38.

**Comment by jimhester** [comment]
Yes this will work once dplyr is using vctrs functions for `case_when()`, and really it is a error in the design of `case_when()` that it does not already.

In the meantime you can just use `unclass()`, e.g.

``` r
x <- "bar"

dplyr::case_when(
  x == "foo" ~ "x is foo",
  TRUE ~ unclass(glue::glue("x is {x}!"))
)
#> [1] "x is bar!"
```

<sup>Created on 2019-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by isteves** [comment]
Great, thank you both!  Glad to hear that the fix is in progress.
