### ISSUE TITLE
vec_c(<character>, <glue>)

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/glue#166]
``` r
library(vctrs)
library(glue)

vec_c("", glue(""), .ptype = character())
#> Error: Can't cast <glue> to <character>.
vec_c("", glue(""), .ptype = glue())
#> Error: Can't cast <glue> to <glue>.
```

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by yutannihilation** [comment]
This should have been fixed on vctrs side in https://github.com/r-lib/vctrs/issues/497 (c.f. #142), so I guess this is some regression of vctrs.

**Comment by jimhester** [comment]
I believe this should be fixed with https://github.com/tidyverse/glue/pull/172
