### ISSUE TITLE
Ignoring NAs in glue_collapse()

### ISSUE THREAD

**Issue by kbzsl** [tidyverse/glue#171]
In some circumstances I miss the option to simply ignore/drop the NAs in the `glue_collapse()`.

```r
to_collapse = c("a", "b", "c")
glue::glue_collapse(to_collapse, sep = ", ")
#> a, b, c

to_collapse = c("a", NA_character_, "c")
glue::glue_collapse(to_collapse, sep = ", ")
#> NA
```
Would it make sense to include an `na.rm` option?

**Comment by shrektan** [comment]
Why not just `glue::glue_collapse(na.omit(to_collapse), sep = ", "))`?

**Comment by kbzsl** [comment]
Thank you, it’s a working solution. On the other hand, it would be a bit more elegant/simple having that option.

**Comment by jimhester** [comment]
I think in this case composition with `na.omit()` as suggested is better than a new option.
