### ISSUE TITLE
Add an argument to allow return class specification

### ISSUE THREAD

**Issue by matthewrspiegel** [tidyverse/glue#173]
I'm using `glue()` as a replacement for `paste()` and quite often I run into issues where a glue object is not accepted as an argument where a character (result of `paste()`) is. 

Below is an example of this. 

Could there be an argument added to glue to allow the user to specify the class of the object that gets returned? I could see this also being useful for situations when you are gluing numbers together and want to return a numeric instead of a glue object.

```r
## install.packages(c("glue", "dpyr"))
library(glue)
library(dplyr)

data(mtcars)
x <- 2:3


# This does not work --------------------------------------------------

mtcars %>% 
  mutate(
    wt2 = wt + rnorm(1),
    wt3 = wt + rnorm(1),
    wt4 = wt + rnorm(1),
    ) %>% 
  filter_at(vars(glue("wt{x}")), any_vars(between(., 2.5, 2.6)))


# This does work ------------------------------------------------------

mtcars %>% 
  mutate(
    wt2 = wt + rnorm(1),
    wt3 = wt + rnorm(1),
    wt4 = wt + rnorm(1),
  ) %>% 
  filter_at(vars(glue("wt{x}") %>% as.character()), any_vars(between(., 2.5, 2.6)))
```

**Comment by jimhester** [comment]
This should be fixed by https://github.com/tidyverse/glue/pull/172
