### ISSUE TITLE
[Request] Consider adding `glue_print()`

### ISSUE THREAD

**Issue by tzakharko** [tidyverse/glue#175]
I am using `glue` to output nicely formatted reports, which involves a lot of printing. This produces a lot of lines looking like this:

```r
print(glue(...))
```

It would be nice if there was a simple wrapper that combines these calls, e.g.

```r
print_glue(...)
```

This would be a trivial addition and I'd be happy to supply a pull request if you think this convenience feature would fit the spirit of the package.

**Comment by jimhester** [comment]
If you are using glue in the top level then auto-printing should suffice. If not than I would suggest you define a `print_glue()` yourself and then use that.

I don't think it is appropriate to include in the glue package.
