### ISSUE TITLE
Failed to install from Github

### ISSUE THREAD

**Issue by jestarr** [tidyverse/glue#176]
I have been unable to install the most recent `dev` version of `glue`.  I've tried restarting my session in R before installing the `dev` version as a solution.  

The error I am getting is:
```r
devtools::install_github("tidyverse/glue")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/glue@master
√  checking for file 'C:\Users\jstarr\AppData\Local\Temp\RtmpGyrbti\remotes2d5c596687d\tidyverse-glue-5010cc6/DESCRIPTION' (626ms)
-  preparing 'glue':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'glue_1.3.2.tar.gz'
   
Installing package into ‘C:/Users/jstarr/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'glue' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/jstarr/Documents/R/win-library/3.6/glue'
* restoring previous 'C:/Users/jstarr/Documents/R/win-library/3.6/glue'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\jstarr\Documents\R\win-library\3.6\00LOCK-glue\glue\libs\x64\glue.dll to C:\Users\jstarr\Documents\R\win-library\3.6\glue\libs\x64\glue.dll: Permission denied
* removing 'C:/Users/jstarr/Documents/R/win-library/3.6/glue'
* restoring previous 'C:/Users/jstarr/Documents/R/win-library/3.6/glue'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\jstarr\Documents\R\win-library\3.6\00LOCK-glue\glue\libs\x64\glue.dll to C:\Users\jstarr\Documents\R\win-library\3.6\glue\libs\x64\glue.dll: Permission denied
Execution halted
Error: Failed to install 'glue' from GitHub:
  (converted from warning) installation of package ‘C:/Users/jstarr/AppData/Local/Temp/RtmpGyrbti/file2d5c5d2a7b2e/glue_1.3.2.tar.gz’ had non-zero exit status
```

**Comment by jimhester** [comment]
You need to make sure glue is not loaded in your current or any other R session. Windows locks open DLLs.

You will have to use `remotes::install_dev("glue")` to install the dev version of glue, as glue is a dependency of devtools, so using devtools implicitly loads glue (and causes this issue).

**Comment by jestarr** [comment]
Thanks @jimhester .  Unfortunately it isn't working.  I'm now getting this error:
```
remotes::install_dev("glue")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo tidyverse/glue@master
Running `R CMD build`...
* checking for file 'C:\Users\jstarr\AppData\Local\Temp\RtmpWSc5wA\remotes2e38101e862\tidyverse-glue-5010cc6/DESCRIPTION' ... OK
* preparing 'glue':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'glue_1.3.2.tar.gz'
Installing package into ‘C:/Users/jstarr/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'glue' ...
** using staged installation
** libs

*** arch - i386
Error in system(cmd) : (converted from warning) 'make' not found
* removing 'C:/Users/jstarr/Documents/R/win-library/3.6/glue'
Error: Failed to install 'glue' from GitHub:
  (converted from warning) installation of package ‘C:/Users/jstarr/AppData/Local/Temp/RtmpWSc5wA/file2e3877c4215a/glue_1.3.2.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
3: In missing_devel_warning(pkgdir) :
  Package glue has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
```
I tried uninstalling and reinstalling Rtools, and it didn't fix the problem.

**Comment by jimhester** [comment]
The error message tells you what is wrong...

> Package glue has compiled code, but no suitable compiler(s) were found. Installation will likely fail. Install Rtools (https://cran.r-project.org/bin/windows/Rtools/)

You need to [install Rtools](https://rstats.wtf/set-up-an-r-dev-environment.html#windows-system-prep) before you can install source packages with compiled code on Windows.

**Comment by jestarr** [comment]
This fixed my problem: https://github.com/rstudio/rstudio/issues/3563#issuecomment-552245641

**Comment by Jimbilben** [comment]
@jestarr in the comment you link to:

Below is the code I use for setting up RCpp as suggested by others.
library(inline)
library(Rcpp)
library(RcppArmadillo)
library(devtools)
Sys.setenv(PATH = paste("C:/Rtools/bin","C:/Rtools/mingw_64/bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")

#Add this line to .Rprofile
Sys.setenv(PATH = paste("C:/Rtools/bin", Sys.getenv("PATH"), sep=";"))

Did you just literally type that code in and it got the install working? And where do you add the final line? - I can't find anything in my computer called .Rprofile

**Comment by Jimbilben** [comment]
@jestarr in the comment you link to:

Below is the code I use for setting up RCpp as suggested by others.
library(inline)
library(Rcpp)
library(RcppArmadillo)
library(devtools)
Sys.setenv(PATH = paste("C:/Rtools/bin","C:/Rtools/mingw_64/bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")

#Add this line to .Rprofile
Sys.setenv(PATH = paste("C:/Rtools/bin", Sys.getenv("PATH"), sep=";"))

Did you just add the final line to the .Rprofile file at the bottom of it? I'm struggling as it says I don't have administrator privileges to change files in that location, but I'm the only person using this computer?!
