### ISSUE TITLE
Glue failure

### ISSUE THREAD

**Issue by syracusepro** [tidyverse/glue#178]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Glue not running and error

```r
# insert reprex here
# Libraries ----
library(tidyquant)
library(furrr)
library(plotly)

ERROR: failed to lock directory 'C:/Users/syrac/Documents/R/win-library/3.6' for modifying
Try removing 'C:/Users/syrac/Documents/R/win-library/3.6/00LOCK-glue'
Warning in install.packages :
  installation of package ‘glue’ had non-zero exit status

```

**Comment by rjpat** [comment]
So `plotly` is attaching the `ggplot2` package which is [trying to access](https://github.com/tidyverse/ggplot2/blob/master/NAMESPACE#L658) `glue` via the namespace.

The reason it is failing is that the `glue` original install failed and has left this locked file. If you delete the folder in your local package location on your machine and reinstall this should work
```
install.packages("glue")
```

**Comment by syracusepro** [comment]
Thanks a lot.
