### ISSUE TITLE
glue + pool now don't go well together

### ISSUE THREAD

**Issue by pachamaltese** [tidyverse/glue#179]
I upgraded to last `glue` version on CRAN (1.3.2) and the same for pool (0.1.4.3) and now `glue_sql` fails when used with `pool::dbPool()`

see here: https://github.com/tradestatistics/plumber-api/blob/master/queries.R#L302-L306
this used to be https://github.com/tradestatistics/plumber-api/blob/61c53fd97391e87a7bf92a7f7cb4ff8cdc88c786/queries.R#L305-L310

but keeping `glue_sql` now returns
```    
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Pool", "character"’
```

**Comment by pachamaltese** [comment]
in feb 11th, glue 1.3.0 with pool 0.1.4.2 worked well together, see
https://github.com/tradestatistics/packrat-library/tree/4de012511cf1735df6048f8166b218d22aff5ee5/packrat/src

**Comment by fmannhardt** [comment]
A possible workaround is to create the following local function until this has been fixed (I guess missing methods in the `pool` package, so adding an issue there):

```
glue_sql <- function(..., .con) {
  connection <- pool::poolCheckout(.con)
  on.exit(pool::poolReturn(connection))  
  glue::glue_sql(..., .con = connection, .envir = parent.frame())  
}
```

**Comment by emillykkejensen** [comment]
Any ETA on a fix? :)

**Comment by jimhester** [comment]
This is an issue with pool, it needs to include the necessary method, there isn't anything to do in glue.
