### ISSUE TITLE
Feature request: syntax highlighting with Glue

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/glue#186]
I much prefer using glue over paste0 and other equivalent solutions. One of the main criticisms that I've heard, however, is that glue doesn't support syntax highlighting within strings and interpolations can be easily lost in a large string. In this case, there is R code that outputs SQL scripts and glue makes it much easier to see what the final SQL script will actually look like over paste0, but there isn't syntax highlighting to differentiate interpolations from the rest of the string.

I wanted to 1) call that out as an issue that some people have with it's current implementation and 2) ask if there are patterns that would help these people adopt glue by giving them syntax highlighting ~somehow~

**Comment by jimhester** [comment]
There unfortunately isn't anything we can do in the glue package to address this. This is something that code editors would have to enable, but doing so is complicated by the fact that there are now a number of functions which take glue style strings.
