### ISSUE TITLE
glue_[data]_sql's asterisk notation fails on an SQL vector

### ISSUE THREAD

**Issue by pnacht** [tidyverse/glue#198]
`glue_sql`'s asterisk notation is very useful for concatenating a vector into a comma-separated list. However, it doesn't seem to work when the vector contains DBI::SQL elements.

See the MWE below*:

```r
library(DBI)

packageVersion("glue")
#> ‘1.4.1’

con <- dbConnect(RSQLite::SQLite(), ":memory:")

a <- letters[1:3]
glue::glue_sql("{a*}", .con = con)
#> <SQL> 'a', 'b', 'c'

a <- SQL(letters[1:3])
glue::glue_sql("{a*}", .con = con)
#> <SQL> a
#> <SQL> b
#> <SQL> c
```

Looking into the `glue` source code, the problem seems to be in the definition of `glue:::sql_quote_transformer` (trimming the irrelevant portions):

```
function (connection, .na) 
{
    # [...]
    function(text, envir) {
        should_collapse <- grepl("[*]$", text)
        if (should_collapse) {
            # [...]
        }
        m <- gregexpr("^`|`$", text)
        is_quoted <- any(m[[1]] != -1)
        if (is_quoted) {
            # [...]
        }
        else {
            res <- eval(parse(text = text, keep.source = FALSE), 
                envir)
            if (inherits(res, "SQL")) {
                return(res)
            }
           # [...]
        }
        if (should_collapse) {
            res <- glue_collapse(res, ", ")
        }
        # [...]
        res
    }
}
```

Specifically, both cases get `should_collapse = TRUE` and `is_quoted = FALSE`. However, the `else` section of the `if (is_quoted)` block contains a check for whether the contents inherit from SQL, in which case they are immediately returned, before the collapse is actually performed at the end of the function.

If of interest, this situation arose because I was trying to write the following statement:

```SQL
UPDATE f
SET a = 0
FROM foo f
INNER JOIN (VALUES {values*})
            v(id, a)
  ON  f.Id = v.Id
```

where `{values}*` contains the vector of results from a previous `glue` statement built from a dataframe (`oldFoo`):

```r
values <- glue::glue_data_sql(
        "({id}, {a})",
        .x = oldFoo,
        .con = con)
```

Since `{id}` and `{a}` don't have an asterisk, this converts `oldFoo` into a vector of SQL strings, which I'd then hoped to collapse into a comma-separated list as expected by the `VALUES` SQL statement.

Interestingly, this problem didn't exist in previous versions of `glue`: [this online compiler](https://rextester.com/ZIJTW78734) uses glue 1.2.0 and it works. Looking at `glue:::sql_quote_transformer`'s source code on that version, we see it was different and didn't include the "if SQL then return" block.

---

\* To be perfectly transparent, the MWE above contains a lie: my actual case uses a `pool` object pointing to an SQL Server database, not an SQLite connection. But this would seem irrelevant to the matter at hand.

**Comment by hadley** [comment]
Looks like this has been fixed:

``` r
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

vars <- DBI::SQL(letters[1:3])
glue::glue_sql("SELECT {vars*} FROM TABLE", .con = con)
#> <SQL> SELECT a, b, c FROM TABLE
```

<sup>Created on 2023-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
