### ISSUE TITLE
sprintf_transformer in transformers vignette is restricted to numeric formatting?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/glue#199]
Raised here originally:

https://stackoverflow.com/q/63731098/3576984

Basically I want a way for `glue` to conveniently replicate a `sprintf` call with 0-padding like:

```
sprintf('%03d', 34)
# [1] "034"
```

I found the `transformers` vignette but the implementation there hard-codes numeric (`f`) formats.

@MrFlick provides what looks to me like a more robust vesion of `sprintf_transfomer` that hews closer to the Python `f''` strings implementation (cf `f{34:03d}` in Python 3.7).

I am happy to file a PR but want to check first that this is something you want.

(also happy to let MrFlick file; in any case I would properly credit the author)

**Comment by jimhester** [comment]
Sure, would be happy for a PR to improve the the vignette
