### ISSUE TITLE
Escaped Braces Cause Unexpected Input Failure

### ISSUE THREAD

**Issue by brodieG** [tidyverse/glue#2]
```
> f('my name is {name}, but do not \\{messwiththis\\}')
Error in fstring_(x, function(x) paste(collapse = sep, fun(eval(parse(text = x),  : 
  <text>:1:13: unexpected input
1: messwiththis\
                ^
```
Seems to be an fstrings thing since the following parses fine:
```
> 'my name is {name}, but do not \\{messwiththis\\}'
[1] "my name is {name}, but do not \\{messwiththis\\}"
```
Also happy to help if you want help.

**Comment by jimhester** [comment]
The python implementation doubles `{{` to escape `{`, which is what I implemented, so the `messwiththis\\}` is what is trying to parse.

```r
f("my name is {name}, but do not {{messwiththis}}")
#> [1] "my name is Fred, but do not {{messwiththis}}"
```

Still backslash escaping is the norm in R, so we should probably handle it as well.

**Comment by brodieG** [comment]
Ah, it's the parsing of  `messwiththis\` that's failing.  I was confused by the error message.  I think leaving the python only escaping is fine and possibly better than adding two escaping mechanisms and the complexity that implies.

Perhaps instead split the parse/eval steps and provide `try` handling, e.g.:
```
* Error in f(...) : token #2 failed to parse with error: 
  <text>:1:13: unexpected input
  1: messwiththis\

* Error in f(...) : token #2 failed to evaluate with error: 
  ...
```
Obviously the second one isn't applicable for this particular problem.
