### ISSUE TITLE
Using glue() with pipes - double printing

### ISSUE THREAD

**Issue by lmeninato** [tidyverse/glue#201]
So usually in a pipe we use "." to not pass the left-hand side of the pipe to the first parameter. 
For instance:
```
1:5 %>% c(1:3, . , 1:3)
 # [1] 1 2 3 1 2 3 4 5 1 2 3
```
But it doesn't seem to work properly with glue:
```
"bob" %>% glue("hello {.}")
 # [1] bobhello bob
# I'd expect "hello bob" ...
```
I'm sure there's a simple fix/workaround out there, but I couldn't find anything online regarding this issue. The pipe is pretty central to the tidyverse, but I understand if the glue wasn't meant to be used with "unnamed" variables (such as the pipe's (.)), so the solution might just be some documentation/awareness around this, rather than changing glue to work with the above issue. 

Using R 3.6.2 and glue 1.4.2

**Comment by lmeninato** [comment]
Actually looks like this more of an issue with how the pipe handles using the placeholder (.) when it appears in a nested expression.
[Pipe documentation link](https://magrittr.tidyverse.org/#re-using-the-placeholder-for-attributes)

We can actually solve the problem by just adding brackets around the glue command in the pipe:
```
"bob" %>% 
  {glue("hello {.}")}
# [1] hello bob
```
Would you guys be interested in a pull request mentioning this in the documentation? Might not be necessary since it's referenced indirectly in the Magrittr documentation.

**Comment by jimhester** [comment]
Sure adding an example to the glue documentation about this seems worthwhile.
