### ISSUE TITLE
Better handling of empty subqueries in glue_sql

### ISSUE THREAD

**Issue by asitemade4u** [tidyverse/glue#204]
I am very pleased with the modularity allowed by `glue_sql` when writing SQL queries, more specifically **PostgreSQL** queries.
There is a case that could be better covered though: when a subquery is optional and therefore sometimes **empty**.
In that case, `glue_sql` returns an empty string between single quotes instead of returning a space/empty string, which, IMO, would be preferable.

```R
oriidt <- "thetable"
orisch <- "theschema"
sqladd <- "" # the additional query here is empty but could be an addition to the query within WHERE() 
thesql <- glue_sql("UPDATE {`orisch`}.{`oriidt`} AS OUT SET act_key = '4' WHERE ({sqlsub}) > 1 {sqladd};", .con=cnx)
DBI::dbExecute(cnx, thesql)
```
thesql as returned by glue_sql is:
```R
<SQL> UPDATE "poi"."plc"AS OUT SET act_key = '4' WHERE (SELECT COUNT(*) FROM "poi"."plc" AS INR WHERE INR."nam" = OUT."nam ' ') > 1;
```
The single quotes at the very end prevent the query to be executed.

**Comment by asitemade4u** [comment]
BTW I have also tested this with a subquery that equals:
- `NULL`
- `NA`
And an empty string between single quotes is still returned, which should definitely not be the case (I understand that an empty string might be usefully returned in the case of an input empty string, but `NULL` and `NA` should definitely not).

**Comment by jimhester** [comment]
You need to use `DBI::SQL("")`, rather than just `""`, e.g.

``` r
library(glue)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

oriidt <- "thetable"
orisch <- "theschema"
sqladd <- DBI::SQL("") # the additional query here is empty but could be an addition to the query within WHERE() 
sqlsub <- DBI::SQL("select COUNT(*) from tbl")
thesql <- glue_sql("UPDATE {`orisch`}.{`oriidt`} AS OUT SET act_key = '4' WHERE ({sqlsub}) > 1 {sqladd};", .con=con)

thesql
#> <SQL> UPDATE `theschema`.`thetable` AS OUT SET act_key = '4' WHERE (select COUNT(*) from tbl) > 1 ;
```

<sup>Created on 2020-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by asitemade4u** [comment]
Thanks Jim, that works!
