### ISSUE TITLE
Better handing of Schemas of PostgreSQL in glue_sql

### ISSUE THREAD

**Issue by asitemade4u** [tidyverse/glue#205]
When using `DBI::dbExecute()` and `glue` and a PostgreSQL database I can write the schema before the table, separated by a dot, thus:
```R
oritbl <- "theschema.thetable"
thesql <- glue("SELECT COUNT(*) FROM {`oritbl`}")
DBI::dbExecute(cnx, thesql)
```
now `thesql` is equal to:
`SELECT COUNT(*) FROM theschema.thetable`
as was expected.

But when I use `glue_sql` instead of `glue`, `thesql` is equal to:
`SELECT COUNT(*) FROM "theschema"."thetable"`
which is **not executable** because of the double quotes around `"theschema"`.

Could you detect the presence of a schema before the table name and not quote it?

**Comment by jimhester** [comment]
You need to use `DBI::Id()` to construct identifiers with multiple parts. e.g.

`DBI::Id(schema = "theschema", table = "thetable")`

**Comment by asitemade4u** [comment]
Yes, it works like that. Besides the code is now more portable between 
databases.

Thanks!
