### ISSUE TITLE
glue_sql: Weird quoting issue with embedded function

### ISSUE THREAD

**Issue by asitemade4u** [tidyverse/glue#207]
I face a weird quoting issue.

Here is the circumstance:
I have a function `sq2_tblful` that returns the fully qualified PostgreSQL name of a table by its name; by example:

```R
oriidt <- "tbl"
tbl <- sq2_tblful(oriidt)
```

`tbl` is now equal to `"rnk"."tbl"` (I am using `DBI::Id` to get the fully qualified name as per your previous recommendation).

Now, as allowed (?), I insert the function `sq2_tblful` into a SQL expression, thus:
```R
thesql <- glue_sql("SELECT pst_formula AS tno FROM {`sq2_tblful(tblidt)`} WHERE nam='{`oriidt`}';", .con=cnx)
```
The rationale is that I want to avoid any variable and have a compact, self-sufficient, executable expression I can execute from R using `glue_sql`.

The embedded function is well understood but I get the following SQL expression, which yields a wrong result because of the double quoting of `'"ppl"'`:
```SQL
SELECT pst_formula AS tno FROM "rnk"."tbl" WHERE nam='"ppl"';
```
The correct SQL expression should be:
```SQL
SELECT pst_formula AS tno FROM "rnk"."tbl" WHERE nam='ppl';
```

Please help.

Stephen

**Comment by asitemade4u** [comment]
Follow up.
In fact, the embedded functiuon (which is well understood) is not the culprit: it does the same when I replace it with a variable.
The reason of the issue, IMO, is the form of fully qualified table names in PostgreSQL that are sourrounded by double quotes, thus: `"rnk"."tbl"`

**Comment by jimhester** [comment]
Use `{oriidt}`, without backticks if you don't want quoting.

These sorts of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer).
