### ISSUE TITLE
glue_sql does not convert integers to strings (which glue does)

### ISSUE THREAD

**Issue by asitemade4u** [tidyverse/glue#208]
I am surprised that `glue_sql` does not convert integers to strings and generates an error (whereas `glue` manages them well and converts them on the fly).
Thus: 
```R
myinteger <- 1
thesql <- glue_sql("SELECT nam FROM {`mytable`} WHERE tbl_key='{`myinteger`}';", .con=cnx)
```
lifts the error:
`
Error: x must be character or SQL
`
and is not executed by the database.

Whereas:
```R
myinteger <- thesql <- glue_sql("SELECT nam FROM {`mytable`} WHERE tbl_key='1';", .con=cnx)
```
Works fine.

What am I doing wrong?

**Comment by jimhester** [comment]
This quotes the identifier and should be used for SQL identifiers, such as table or column names.

```r
{`xyz`}
```

This just returns the value without quoting (no backticks)
```r
{xyz}
```

You should use the latter for values like `myinteger`.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
