### ISSUE TITLE
glue_data() ignores .envir when .x is an environment

### ISSUE THREAD

**Issue by egnha** [tidyverse/glue#21]
When the `.x` argument of `glue_data()` is an environment, the evaluation of `...` takes place in `.x` and not in `.envir`, contrary to the documented role of `.envir`. In particular, if `...` is not in `.x`, then `glue_data()` will fail.

Is this the intended behavior?

Example:
```R
env <- new.env(parent = baseenv())
env$a <- "This is 'a'"

text <- "{a}"

glue_data(.x = env, text)
## Error in eval(x, envir = data, enclos = envir) : object 'text' not found
```
`glue_data()` has not evaluated `text` in `.envir = parent.frame()`.

Naively, I would expect `.x` to be used solely for object look-up, i.e., as if `.x` were coerced to a list:
```R
glue_data(.x = as.list(env), text)
## This is 'a'
```

**Comment by jimhester** [comment]
You need to modify the parent of your environment to be `.GlobalEnv` or `parent.frame()` rather than `baseenv()` if you you looking for that behavior. You are explicitly saying you want to perform lookup only in the immediate environment and baseenv in your example.

**Comment by egnha** [comment]
Yes, correct. However, it still seems that there is an inconsistency with the API: if `.x` is a data frame or list, it is used for object look-up, while if `.x` is an environment, it is also used for evaluation, and that lead to behavior that clashes with what one would naively expect.

**Comment by egnha** [comment]
Moreover, assuming `glue_data()` is altered to treat lists, environments and data frames equally (as "containers"), then the current behavior of `glue_data()` for `.x` an environment can be mimicked with (an admittedly ugly invocation) `eval(substitute(glue(., .envir = env), list(. = text)))`. That might be an acceptable trade-off for a more consistent API.
