### ISSUE TITLE
glue() doesn't work with data.table

### ISSUE THREAD

**Issue by markfairbanks** [tidyverse/glue#211]
I'm not sure if this is a {data.table} issue or a {glue} issue.

Basically `glue()` doesn't work inside of a {data.table} `[ ]` call unless you use a workaround:

``` r
library(data.table)
library(glue)
library(dplyr)

test_df <- data.table(a = letters[1:3], b = letters[1:3])

# Works with dplyr
mutate(test_df, new = glue("{a}_{b}"))
#>    a b new
#> 1: a a a_a
#> 2: b b b_b
#> 3: c c c_c

# Fails with data.table
copy(test_df)[, new := glue("{a}_{b}")][]
#> Error in eval(parse(text = text, keep.source = FALSE), envir): object 'a' not found

# Workaround for data.table using `.SD` as the evaluation environment
copy(test_df)[, new := glue("{a}_{b}", .envir = .SD)][]
#>    a b new
#> 1: a a a_a
#> 2: b b b_b
#> 3: c c c_c
```
Rdatatable/data.table#4879

**Comment by jimhester** [comment]
Yes, this is due to the way that data.table sets up the environment chain.

You either need to use `glue("{my_var}", .envir = .SD)` or use `glue_data(.SD, "{my_var}")`.

I don't think there is really anything we could change in glue to improve this, so I will close this issue.

**Comment by AltfunsMA** [comment]
I was just bitten by this (while using @markfairbanks great tidytable package); perhaps it deserves a quick mention in the docs? `?glue` # examples currently says you can use it on a number of options, but it's unclear whether this is an exhaustive list or whether there are well-known incompatibilities.

**Comment by markfairbanks** [comment]
@AltfunsMA - FYI if you update tidytable `glue()` now works. I built in a workaround until `data.table` fixes the issue on their end.

``` r
library(tidytable)
library(glue)

df <- tidytable(x = c("a", "b", "c"))

df %>%
  mutate.(x_end = glue("{x}_end"))
#> # A tidytable: 3 × 2
#>   x     x_end 
#>   <chr> <glue>
#> 1 a     a_end 
#> 2 b     b_end 
#> 3 c     c_end
```
