### ISSUE TITLE
Shorthand for coercing glue(...) to character (e.g. for if_else or case_when)

### ISSUE THREAD

**Issue by orgadish** [tidyverse/glue#220]
I often find myself using `glue(...)` within `if_else` or `case_when`, mixed with simple strings. In order for this to work I have to explicitly coerce the glue object to character (or the strings to glue). It would be very convenient if there were a shorthand, e.g. `glue_chr(...)` which automatically returned the result as a pure character class.

```r
d <- tibble(x = 1:10)

mutate(d, y = case_when(
    x <= 3 ~ "x <= 3", 
    x >= 8, "x >= 8",
    TRUE ~ glue("x = {x}") %>% as.character
))

# With shorthand
# ... TRUE ~ glue_chr("x = {x}") ...
```

Unfortunately, defining a utility function naively didn't work because of the environment.
```r
# This function will not work in the use case above, error: "object 'x' not found"
glue_chr <- function(...) as.character(glue(...))
```

**Comment by jimhester** [comment]
You need to pass the `.envir` argument on to the glue call for your helper function, e.g.

``` r
g <- function(..., .envir = parent.frame()) unclass(glue::glue(..., .envir = .envir))

library(dplyr)

d <- tibble(x = 1:10)

mutate(d, y = case_when(
    x <= 3 ~ "x <= 3", 
    x >= 8 ~ "x >= 8",
    TRUE ~ g("x = {x}")
))
#> # A tibble: 10 × 2
#>        x y     
#>    <int> <chr> 
#>  1     1 x <= 3
#>  2     2 x <= 3
#>  3     3 x <= 3
#>  4     4 x = 4 
#>  5     5 x = 5 
#>  6     6 x = 6 
#>  7     7 x = 7 
#>  8     8 x >= 8
#>  9     9 x >= 8
#> 10    10 x >= 8
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by orgadish** [comment]
Thanks! I had tried the same, but was passing in `parent.frame(2)` thinking I needed to jump up two layers, as opposed to simply passing in the existing environment.

I still think this would be a useful function to have natively as part of the `glue` package, but being able to write the helper this easily does significantly reduce the urgency.

**Comment by jimhester** [comment]
~
