### ISSUE TITLE
Comment inside {} suppresses output

### ISSUE THREAD

**Issue by gaborcsardi** [tidyverse/glue#224]
I realize this is an edge case, and you probably would not write code like this, but it may happen if the code within `{}` is machine-generated:

```r
c(glue::glue("pre {1+5 # never mind me} post"))
#> [1] "pre "
```

It is not entirely straightforward what the output should be, maybe the interpolation should end at `}`, and it then it would be `"pre 6 post"`?

**Comment by jimhester** [comment]
This seems to be a case that is not properly handled, the code assumes comments will always end with a newline.

e.g. this works

``` r
glue::glue("pre {1+5 # never mind me
} post")
#> pre 6 post
```

<sup>Created on 2021-09-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>```

**Comment by gaborcsardi** [comment]
That makes sense. Doe you think it would make sense to "fix" this for the case without a newline? Would you review a PR for this?

**Comment by jimhester** [comment]
yeah

**Comment by gaborcsardi** [comment]
Now I am not sure anymore how to "fix" this. E.g. this seems fine, and we probably don't want to look for closing delims eagerly.

```r
❯ glue::glue("pre {1 + 5 + # never mind the }\n 4} post")
pre 10 post
```

OTOH the original example surely does not make sense, so maybe that should be an error? I.e. if the string ends in `comment` state, that could be an error?

**Comment by jimhester** [comment]
Yeah, I think if we end in a comment state making that an error makes sense to me
