### ISSUE TITLE
Allow custom delimiters

### ISSUE THREAD

**Issue by baptiste** [tidyverse/glue#23]
`{` `}` would make it hard to work with some languages such as TeX.

**Comment by egnha** [comment]
You can implement custom delimiters by string substitution: substitute custom delimiters by glue's delimiters, then apply `glue`.

Here's one way to do this. First, make a delimiter converter:
```R
redelimiter <- function(left, right) {
  redelim <- list(
    c("\\{",   "{{"), c("\\}",   "}}"),
    c(left, "{"),  c(right, "}")
  )  
  # if performance becomes an issue, don't use Reduce()
  function(text) {
    Reduce(function(x, .) gsub(.[1], .[2], x), redelim, init = text)    
  }
}
```
For example, to convert `<<`, `>>` delimiters to glue's delimiters, apply `redelimiter("<<", ">>")` to your string:
```R
redelimiter("<<", ">>")("The value of $e^{2\\pi i}$ is $<<one>>$.")
#> [1] "The value of $e^{{2\\pi i}}$ is ${one}$."
```
Modifying `glue()` to work with custom delimiters is just a matter of “redelimiting” before calling glue; the only thing one has to be careful about is to pass the interpolation arguments to `glue()`, _unevaluated_.
```R
glue_with_delim <- function(left, right) {
  redelim <- redelimiter(left, right)
  restring <- function(env, ...) {
    strings <- eval(substitute(alist(...)))
    not_named <- !glue:::has_names(strings)
    strings[not_named] <- redelim(
       vapply(strings[not_named], eval, character(1), envir = env)
    )
    strings
  }
  # same formals as glue()
  function(..., .sep = "", .envir = parent.frame()) {
    strings <- restring(parent.frame(), ...)
    eval(as.call(c(glue::glue, strings, .sep = .sep, .envir = .envir)))
  }
}
```
With `glue_with_delim()`, you can make a version of `glue()` adapted to `<<`, `>>` delimiters, say:
```R
gum <- glue_with_delim("<<", ">>")

text1 <- "The value of $e^{2\\pi i}$ is $<<one>>$."
text2 <- "The value of $e^{2\\pi i} + 1$ is $<<two>>$."
gum(text1, text2, one = Re(exp(2i * pi)), two = one + 1, .sep = "\n")
#> The value of $e^{2\pi i}$ is $1$.
#> The value of $e^{2\pi i} + 1$ is $2$.
```
@jimhester Do you think custom delimiters should remain DIY?

**Comment by jimhester** [comment]
I think this is an interesting solution. I think modifying the C code to handle this case is probably a better way to go in the package, but you can definitely use something like this until that is implemented.
