### ISSUE TITLE
"Inputs are not vectorized" 🤔

### ISSUE THREAD

**Issue by jennybc** [tidyverse/glue#24]
> Inputs are not vectorized

I'm puzzled by this statement in the main help file. The example `mtcars %>% glue_data("{rownames(.)} has {hp} hp")` seems to immediately go counter to this (not to mention lots of usage I've made). Can this be reworded so the meaning is more clear?

**Comment by jimhester** [comment]
I think it can be removed, originally inputs were not vectorized, but now they are.
