### ISSUE TITLE
waldo version requirement for tests

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/glue#252]
I know it's not a strict requirement to have version requirements for Suggested packages, but it took me quite a while to figure this out, so I figure I'd flag it.

I'm trying to update glue from 1.4.2 --> 1.6.0.

It appears `waldo` needs to be of a certain version for this to work. Otherwise we get a pile of test failures like:

```
── Failure (Line 7): glue and glue_data safe do not execute code ─────────────────────
glue("{1 + 1}") (`actual`) not equal to "2" (`expected`).

`actual` is an S3 object of class <glue/character>, a character vector
`expected` is a character vector ('2')

── Failure (Line 8): glue and glue_data safe do not execute code ─────────────────────
glue_safe("{1 + 1}") (`actual`) not equal to "5" (`expected`).

`actual` is an S3 object of class <glue/character>, a character vector
`expected` is a character vector ('5')
```

Luckily I'm familiar enough with `testthat`/`waldo` internals to recognize the issue from the error message -- `waldo::compare()` sees the classes differ on the objects; what we need is `waldo::compare_proxy()` to have a `glue` method that ignores the `glue` class. But I see a `compare_proxy.glue` method in R/utils.R -- why isn't it taking hold?

The issue appears to be that `compare_proxy()` is never called.

The issue resolves when I update waldo 0.2.5 --> 0.3.1 simultaneously.

I can't tell from reading `waldo`'s NEWS what made the change (looks like 0.3.0 is likely?), nor do I have any easy way to check manually.

**Comment by jennybc** [comment]
I think this is a basis for deciding the minimum version of waldo:

https://github.com/r-lib/waldo/issues/65
https://github.com/r-lib/waldo/commit/d835b2a7cbb7dd96f5bd62e15514893766c31b74

which indicates we want waldo >= v0.3.0.

**Comment by MichaelChirico** [comment]
thanks for investigating!
