### ISSUE TITLE
Let glue class inherit from 'character' class as well for S3 method dispatch

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/glue#26]
Thanks for this great package. glue made my life easier with template strings.

But, one thing I feel a bit frustrated is that some S3 generic methods cannot process the glue object because they don't know the fact `glue` is almost `character`.

```r
generate_msg <- function(x) {
  l <- list(msg = glue::glue('Praise the {x}!'))
  jsonlite::toJSON(l)
}

generate_msg("V8")
#> Error: No method asJSON S3 class: glue

class(glue::glue('Praise the {x}!', x = 'V8'))
#> [1] "glue"
```

I know just using `unclass()` or `as.character` will save me, but is it possible to let `glue` class inherit from `character` class? Or, are there some reason that we have to restrict its class `glue` only?

```r
generate_msg <- function(x) {
  msg <- `class<-`(glue::glue('Praise the {x}!'), c('glue', 'character'))
  l <- list(msg = msg)
  jsonlite::toJSON(l)
}

generate_msg("V8")
#> {"msg":["Praise the V8!"]} 
```

**Comment by jimhester** [comment]
I just changed this on the current devel branch a few days ago, (https://github.com/tidyverse/glue/commit/41a5cfff09cf76b9c726222df6b04b13deb4ffc4). glue objects now inherit from  character as well.

**Comment by yutannihilation** [comment]
Cool. Looking forward to the next release. Thanks!
