### ISSUE TITLE
Update for R-devel

### ISSUE THREAD

**Issue by jennybc** [tidyverse/glue#260]
Via an email from @ltierney on 2022-02-17:

> I'll be committing a change to R-devel soon to experimentally support
a placeholder for the native pipe. This will change an error message
glue is now testing for so glue will fail its tests. In the to be
committed version:
> 
> `glue::glue_col("{_}")`
Error in _ : invalid use of pipe placeholder
> 
> But this could change, so it would be better not to depend on the
specific message.

https://github.com/tidyverse/glue/blob/3da70df68012cc65a9ba18907f70cd5514f16b41/tests/testthat/test-color.R#L45-L54

**Comment by hadley** [comment]
Maybe use different invalid syntax like `{foo(}` ?

**Comment by jennybc** [comment]
Version v1.6.2 is now on CRAN, in which this test has been modified to avoid `_` in its exploration of errors for invalid syntax. I also switched to snapshot tests, which seem more appropriate anyway.
