### ISSUE TITLE
Documentation of `glue_[data_]sql()`'s `.na` argument is slightly inconsistent

### ISSUE THREAD

**Issue by pnacht** [tidyverse/glue#261]
I was looking at glue's documentation to copy its `[type : default-value]` argument definitions and accidentally noticed a tiny error caused by it.

It's a minuscule nitpick in the documentation defined in the sql.R file regarding the `.na` argument.

That argument's documentation is imported from the standard `glue()` functions via `@inheritParams glue`. However, since `glue` utilizes the `[type : default-value]` format for its arguments, `glue_sql`'s `.na` argument is defined as:

```
.na	
     [character(1): ‘NA’]
     Value to replace NA values with. If NULL missing values are
     propagated, that is an NA result will cause NA output.
     Otherwise the value is replaced by the value of .na.
```

This describes `.na`'s default value as `"NA"`, when it is in fact `DBI::SQL("NULL")`.

Consistency would require copying the definition in glue.R and then just changing that `‘NA’` to `DBI::SQL("NULL")`.

Whether it's worth the hassle...

**Comment by jennybc** [comment]
Would you like to make a PR?
