### ISSUE TITLE
Documentation: availability of .open / .close in glue_sql() are not clear from ?glue_sql

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/glue#274]
These parameters are picked from `...` by passing directly to `glue()`, but that's not at all clear from the man page:

https://glue.tidyverse.org/reference/glue_sql.html

> `...`: [expressions] Unnamed arguments are taken to be expression string(s) to format. Multiple inputs are concatenated together before formatting. **Named arguments are taken to be temporary variables available for substitution**.

**Comment by jennybc** [comment]
Do you happen to have an example that demonstrates the type of usage you're thinking of, i.e. usage that works but that's hard for a user to anticipate?

(This would be in addition to enhancing the docs re: `...`.)

**Comment by MichaelChirico** [comment]
glue_sql("SELECT COUNT(*) FROM %tbl%", .open="%", .close="%", .con=conn)

(basically, we need to mention that arguments to glue will be picked up as such)
