### ISSUE TITLE
Feature request: print nicely formatted data frames

### ISSUE THREAD

**Issue by patrickroocks** [tidyverse/glue#277]
When I try to format a `data.frame` the result is quite weird:

```r
glue("Here are two cars:\n {mtcars[1:2,]}")
```

This gives the following output:

```
Here are two cars:
c(21, 21)
Here are two cars:
c(6, 6)
Here are two cars:
c(160, 160)
Here are two cars:
c(110, 110)
[...some more similar lines...]
```

I wrote the the following helper function / workaround:

```r
format_df <- function(df) {
  paste0(capture.output(df), collapse="\n")
}

glue("Here are two cars:\n {format_df(mtcars[1:2,])}")
```

This gives the intended output:

```
Here are two cars:
              mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

I think this could be pretty easy integrated in `glue`: For each variable where `is.data.frame` is true, such a helper function is called to transform the data.frame to a multiline string.

Would this be a feature of interest for the `glue` library?

**Comment by patrickroocks** [comment]
I found a better "workaround" using the transformer parameter:

```r
library(glue)

format_printable <- function(val) {
  if (is.atomic(val)) val
  else paste0(capture.output(print(val)), collapse="\n")
}

printable_transformer <- function(text, envir) {
  expr <- parse(text = text, keep.source = FALSE)
  final_expr <- quote(format_printable())
  final_expr[[2]] <- expr[[1]]
  eval(final_expr, envir)
}

catf <- function(...) {
  cat(glue(..., .envir = parent.frame(), .sep = "\n", .trim = FALSE, 
           .transformer = printable_transformer))
  cat("\n")
}
```

With this I can simply write `catf("Here are two cars:\n{mtcars[1:2,]}")` and get the desired output...

But I am questioning why this is not the default behavior of `glue`? Printing something in R using the overloaded `print(...)` function seems to be the canonical way. Coercing data.frames in character vectors and doing a vectorized pasting looks not like something could really intend this...?

**Comment by hadley** [comment]
I _think_ that this is out of scope for glue, since it's primarily about building strings from combinations of vectors (since it's fundamentally vectorised), not arbitrary objects.
