### ISSUE TITLE
collapse() when x has length zero

### ISSUE THREAD

**Issue by jennybc** [tidyverse/glue#28]
It feels like `collapse()` would be more consistent with `glue()` (and more convenient) if it returned `character(0)` if the input has length zero.

``` r
library(glue)
glue("{x}", x = "hi")
#> hi
glue("{x}", x = character(0))
#> character(0)
collapse(x = c("hi", "bye"), last = " and ")
#> [1] "hi and bye"
collapse(x = c(NULL, "bye"), last = " and ")
#> [1] "bye"
collapse(x = c("hi", NULL), last = " and ")
#> [1] "hi"
collapse(x = NULL, last = " and ")
#> [1] ""
collapse(x = character(), last = " and ")
#> [1] ""
```

**Comment by jimhester** [comment]
I think this was done deliberately to mimic 
```r
paste(collapse = "", character())
#> ""
```
But I could be easily swayed to return `character()` here...

**Comment by jimhester** [comment]
It is probably a good philosophy to always return 0 length outputs for 0 length inputs, so I will change this.

**Comment by jennybc** [comment]
Yeah I was looking to glue to save me from the behaviour of `paste(collapse = "", character())`. Thanks.
