### ISSUE TITLE
Make set() and resize() static

### ISSUE THREAD

**Issue by mmarko1010** [tidyverse/glue#282]
https://github.com/tidyverse/glue/blob/295279765415bcbfd7505573b85b9fd9a7c5c0b4/src/glue.c#L7

I ran into this crash using embedded R with ggplot2
```
#4  0x00007f60d42af37a in sigactionSegv (signum=11, ip=<optimized out>, context=<optimized out>) at main.c:624
#5  <signal handler called>
#6  0x000000000041b38d in qa (x=0x0) at f.c:2
#7  0x000000000044d3b3 in vx (x=0x0) at v.c:381
#8  0x000000000044d73a in set (v=0x1c4f87b0, x=0x0, f=0x1c4f8270, y=0x0) at v.c:423
#9  0x00007f60b760787c in glue_ (x=0x1c4f8ba0, f=0x1c0bfce8, open_arg=0x1c4da580, close_arg=0x1c4da510,
    comment_arg=0x1c4da430, literal_arg=0x1c4da3f8) at glue.c:172
#10 0x00007f60d4232ad4 in R_doDotCall (ofun=<optimized out>, nargs=<optimized out>, cargs=<optimized out>,
    call=0x1c0b1d80) at dotcode.c:617
```
I am [obviously] not an expert in the Linux loader but it seems like it bound my "set" function (from my v.c) to glue.so (even though mine has 4 args!).
When I made glue's `set()` _static_, the problem went away.  So it might be worth adding static to the two internal functions here.
Thank you.

**Comment by jennybc** [comment]
@mmarko1010 I think @DavisVaughan is correct in thinking that a change we just merged re: symbol visibility for glue in general probably solves your problem as well. I'm closing this in anticipation. Hopefully you are in a position to try out dev glue and confirm this.
