### ISSUE TITLE
Return value not documented

### ISSUE THREAD

**Issue by barryrowlingson** [tidyverse/glue#283]
The documentation for `help(glue::glue)` doesn't have a `Value` section explicitly saying what is returned.

Currently an object of multiple class "glue" and "character" is returned, but I see no documentation on the "glue" class. The only obvious functionality is it makes glued results appear without vector labels or quotation marks:

```
> gs = glue::glue("{sample(letters)}")
> gs
a
e
o
x
y
[etc]
```

which is clearly less friendly than printing as characters, as you'd get if paste()-ing chars or as you get when converting glue to character with as.character or unclass, when it all fits on a couple of lines, shows the index position, and shows these things are quoted character strings:

```
> unclass(gs)
 [1] "a" "e" "o" "x" "y" "i" "j" "c" "s" "h" "q" "k" "r" "f" "l" "n" "z" "m" "u"
[20] "b" "d" "g" "t" "v" "w" "p"
> 
```

Presentation of the class via print.glue aside, the return value ought to be specified in the help and the class should be documented so people who want to use these classes have an interface they can work with.

**Comment by hadley** [comment]
For the print method, one possible option would be to take some of the logic from `str_view()`:

``` r
stringr::str_view(letters[1:10])
#>  [1] │ a
#>  [2] │ b
#>  [3] │ c
#>  [4] │ d
#>  [5] │ e
#>  [6] │ f
#>  [7] │ g
#>  [8] │ h
#>  [9] │ i
#> [10] │ j
```

<sup>Created on 2023-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
