### ISSUE TITLE
cli pluralisation

### ISSUE THREAD

**Issue by oloverm** [tidyverse/glue#288]
Pluralisation is a great feature in [cli](https://github.com/r-lib/cli), could it be brought to glue?

![image](https://user-images.githubusercontent.com/26772530/213668847-fadb3a4d-f5a4-430a-b5d7-f5802256f6f1.png)

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for glue: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
