### ISSUE TITLE
New version of R causes issues with a glued value in `head()`

### ISSUE THREAD

**Issue by edgararuiz** [tidyverse/glue#305]
Using the output of `glue` does not work on R 4.3.0 when used as the `n` value for `head()`. There may be other functions that could have problems, but this is the only one I've identified it for at this time. 

R version 4.0.2

``` r
library(glue)
#> Warning: package 'glue' was built under R version 4.0.5

nrow(head(mtcars, glue("1")))
#> [1] 1

nrow(head(mtcars, glue("{Inf}")))
#> [1] 32
```

<sup>Created on 2023-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

R version 4.3.0

``` r
library(glue)

nrow(head(mtcars, glue("1")))
#> Error in checkHT(n, d <- dim(x)): invalid 'n' - must be numeric, possibly NA.

nrow(head(mtcars, glue("{Inf}")))
#> Error in checkHT(n, d <- dim(x)): invalid 'n' - must be numeric, possibly NA.
```

<sup>Created on 2023-05-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by batpigandme** [comment]
After a little investigation, it looks like the fact that this worked prior to 4.3.0 was a bug, changed to give an error here: https://bugs.r-project.org/show_bug.cgi?id=18357

The behavior in older versions of R was unrelated to glue. For example, in 4.2.3 you'd get the same results with strings that you did with glue:
``` r
nrow(head(mtcars, "1"))
#> [1] 1

nrow(head(mtcars, "7"))
#> [1] 32

nrow(head(mtcars, "Inf"))
#> [1] 32
```
<sup>Created on 2023-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Now, in 4.3.0, those same strings (without glue) also give errors:
``` r
nrow(head(mtcars, "1"))
#> Error in checkHT(n, d <- dim(x)): invalid 'n' - must be numeric, possibly NA.

nrow(head(mtcars, "7"))
#> Error in checkHT(n, d <- dim(x)): invalid 'n' - must be numeric, possibly NA.

nrow(head(mtcars, "Inf"))
#> Error in checkHT(n, d <- dim(x)): invalid 'n' - must be numeric, possibly NA.
```
<sup>Created on 2023-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
