### ISSUE TITLE
Example assumes DBI (>= 1.2.0)

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/glue#324]
https://github.com/tidyverse/glue/blob/9f88e2179fc7aa6ff11214271fd61bba169f925c/man/glue_sql.Rd#L195

Per the NEWS, this style is only valid from DBI v1.2.0:

> Id() now accepts unnamed components (#417). If names are provided, the components are arranged in SQL order (@eauleaf, #427).

But {glue} doesn't have that version stated.

The easiest fix is just to bump the minimum version, but OTOH, is it worth bumping the version requirement just for examples? I leave it up to maintainers :)

**Comment by jennybc** [comment]
Another observation: DBI is only listed in Suggests and, while some methods of "install all my dependencies" might honor a minimum version for a suggested package, I think most don't. So this is a signal mostly aimed at humans.

In any case, this change has already been made in the dev version of glue: https://github.com/tidyverse/glue/commit/84ea0883af55d4b9528ac00c3c340565895a58a8.

**Comment by MichaelChirico** [comment]
> I think most don't

I think you're right -- but even if they don't, they "should", and we can expect it'll be true "eventually"... just that we have no way of detecting any backsliding in the meantime (besides reports from folks like me that install from weird environments 😃)
