### ISSUE TITLE
FR: support vectorized input/ouptut (don't concatenate)

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/glue#328]
Hi,

As for now, it seems impossible to glue a vector without concatenating the result. The output appears always to be a string of length 1.
Yet, `as_glue()` can output a vector so it is surprising that this cannot be done.

It can be very useful to use interpolation and get a vectorized output, for instance when building automated reports where each vector member is then processed into a paragraph.

``` r
library(tidyverse)
library(glue)
```

``` r
name <- "Fred"
age <- 50
glue('My name is {name},',
     'my age next year is {age + 1}.')
#> My name is Fred,my age next year is 51.
```

``` r
# expected feature/workaround
glue_vec = function(...){
  glue(..., .sep="___") %>% 
    str_split_1("___") %>% 
    as_glue()
}
glue_vec('My name is {name},',
         'my age next year is {age + 1}.')
#> My name is Fred,
#> my age next year is 51.
```
<sup>Created on 2024-07-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

This could also be a special case inside `glue()`, with a special value like `.sep=TRUE`.

**Comment by philibe** [comment]
Have you tried ? : 

``` r
library(tidyverse)
library(glue)

name <- "Fred"
age <- 50

your_glue <- sapply( 
  c(
    'My name is {name},',
    'my age next year is {age + 1}.'), 
  glue, USE.NAMES = FALSE
) %>% as_glue()

your_glue
#> My name is Fred,
#> my age next year is 51.
```

``` r

dput(your_glue)
#> structure(c("My name is Fred,", "my age next year is 51."), class = c("glue", 
#> "character"))
```

<sup>Created on 2024-07-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DanChaltiel** [comment]
I'm a bit confused about your comment, what is the difference between the output of your `your_glue()` and of my `glue_vec()`?

**Comment by philibe** [comment]
The output is the same, but the workflow is different: 
- not splitted string 
- vector input, vector output

**Comment by DanChaltiel** [comment]
Indeed, but then I'm afraid you are missing the point of this Feature Request issue.
I'm not asking for another way to write the function (for this I should have gone to StackOverflow), I'm asking if this should be a feature of the `glue` package or just a user-level custom function.
This is a function that I've been using for a while and each time I expect glue to be able to handle it, so maybe I'm not the only one that would benefit from glue supporting this.
Thanks for taking the time to submit your version though!

**Comment by jennybc** [comment]
> if this should be a feature of the glue package or just a user-level custom function

I think the user should map glue over a vector of inputs in this situation. And I do so myself in various places, such as this [wrapper around `glue_data()`](https://github.com/r-lib/gargle/blob/ef00eb0581a8eda05185a3a6348f80cff522dd76/R/roxygen-templates.R#L28-L34) (there's more going on there, but you get the idea).

The treatment of `glue()`'s `...` is firmly established (unnamed inputs are concatenated) and is not something I would mess with.

Relevant write-up of current design thinking about how to use `...`:

https://design.tidyverse.org/dots-data.html

The implication of ☝️ in this discussion is that I think it's best to gather up those "loose parts" in a vector, then use `vapply()` or `purrr::map_chr()` (or a purrr compatibility function) with `glue()`.

``` r
library(glue)

name <- "Fred"
age <- 50
x <- c('My name is {name},', 'my age next year is {age + 1}.')

# works for casual, direct use
map_glue <- function(x) vapply(x, glue, "", USE.NAMES = FALSE)
map_glue(x)
#> [1] "My name is Fred,"        "my age next year is 51."

# moving towards a more safe, general implementation
map_glue <- function(x, .envir = parent.frame()) {
  vapply(x, \(x) glue(x, .envir = .envir), "", USE.NAMES = FALSE)
}
map_glue(x)
#> [1] "My name is Fred,"        "my age next year is 51."
```

As the second version suggests, you can swiftly get into some tricky issues re: which environment is being used for evaluation, when you start programming around and mashing up glue and apply/map functions. So it's best to be explicit.

**Comment by hadley** [comment]
Note that glue already is vectorised, just in the data parts, not the string parts:

``` r
name <- c("Fred", "John")
age <- c(50, 65)
glue::glue('My name is {name} and ', 'my age is {age + 1}.')
#> My name is Fred and my age is 51.
#> My name is John and my age is 66.
```

<sup>Created on 2024-07-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I can't quite imagine how this would work if it was also somehow vectorised over unnamed inputs.
