### ISSUE TITLE
Waldo install fails with dev glue

### ISSUE THREAD

**Issue by gaborcsardi** [tidyverse/glue#331]
I don't know where the error lies, I am merely recording this here:
```
* installing *source* package ‘waldo’ ...
** package ‘waldo’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in get(genname, envir = envir) : object 'compare_proxy' not found
Calls: <Anonymous> ... register_S3_method_delayed -> registerS3method -> get
Execution halted
ERROR: lazy loading failed for package ‘waldo’
* removing ‘/Users/gaborcsardi/Library/R/arm64/4.4/library/waldo’
* restoring previous ‘/Users/gaborcsardi/Library/R/arm64/4.4/library/waldo’
```

**Comment by jennybc** [comment]
I suspect this is related to #310. @hadley do you have any thoughts?

**Comment by hadley** [comment]
I suspect you're right. Maybe this is a bug in R-devel?

**Comment by gaborcsardi** [comment]
IDK if it is a bug in base, but it seems that this has never actually worked. We don't see errors on the CI because we don't build waldo from source, except on R-devel. But it does fail the same way in all R versions I tried, 4.4.1, 4.3.x, 4.2.x, etc. 4.0.5, and also 3.6.3:
```
docker run -ti ghcr.io/r-hub/r-minimal/r-minimal:3.6.3 bash
installr -p -c tidyverse/glue waldo
```

```
** byte-compile and prepare package for lazy loading
Error in get(genname, envir = envir) : object 'compare_proxy' not found
Calls: <Anonymous> ... register_S3_method_delayed -> registerS3method -> get
```

**Comment by hadley** [comment]
Hmmmm, interesting. I will try and figure out what makes `compare_proxy` different from the other method. Or maybe it's just the first loaded?

**Comment by gaborcsardi** [comment]
My (very uneducated) guess is that the difference is that waldo imports glue via `NAMESPACE`, whereas vctrs does not. So when waldo is being installed, glue is loaded, and that triggers the conditional generic, and R tries to load the generic, but since waldo is in a half-loaded state, it cannot. 

So a simple workaround would be (if above is correct) to not import glue in `NAMESPACE` from waldo.

**Comment by hadley** [comment]
Do you have any easier way to test that? I made https://github.com/r-lib/waldo/pull/195.

(This does feel like a bug in R to me, since it means you have to think more about how your packages interact, which our previous solution did not 😬)

**Comment by gaborcsardi** [comment]
Yep, your fix works. This is how to test it easily if you don't want to overwrite your system:
```
docker run -ti ghcr.io/r-hub/r-minimal/r-minimal:4.4.1 bash
installr -p -c tidyverse/glue r-lib/waldo@dont-import-glue
```

I agree that it is a bug in base R. A half-loaded package should not trigger the conditional S3 methods. (Although that'll make waldo'd glue import behave differently at install time than at run time, but still better.)

**Comment by gaborcsardi** [comment]
Base R bug report: https://bugs.r-project.org/show_bug.cgi?id=18776

**Comment by jennybc** [comment]
We've encountered a variant of this problem before, with knitr.

See #253 and #254 (this PR especially contains a lot of write-up).
