### ISSUE TITLE
Feature request/question: Extract the code to be evaluated

### ISSUE THREAD

**Issue by billdenney** [tidyverse/glue#334]
I want to warn users if not all items they pass to a function are passed to a `glue` specification (related to billdenney/ggtibble#13).  As a pseudocode example, I'd like to be able to do something like:

```r
extract_glue_expressions <- function(x) {
  # return all expressions in `x`
}
```

When I looked for the place in the code where this may happen, I found 

https://github.com/tidyverse/glue/blob/05e85e18694929d713fd5b8e25b55abb0c18a2fc/R/glue.R#L179

but, this already does the substitution.

Is there any supported way to get the unevaluated expressions before substitution?

I'd guess if I captured the expression as it goes into this code (https://github.com/tidyverse/glue/blob/05e85e18694929d713fd5b8e25b55abb0c18a2fc/R/glue.R#L150-L176), I could have the list, but that does not appear to be in the current API.

**Comment by billdenney** [comment]
I ended up finding a way to do it via the `.transformer` argument as shown in the PR.  Please let me know what you think.

**Comment by jennybc** [comment]
I don't perceive a general need for this and therefore don't plan to sign up to maintain such a function in glue itself. But yes I agree that leveraging the `.transformer` argument is the right approach. From #335, it looks like you figured out how to define a relatively lightweight helper that does what you need over in ggtibble.

**Comment by billdenney** [comment]
Thanks for the quick review, and that makes sense to me.
