### ISSUE TITLE
Issues with UTF-8 strings

### ISSUE THREAD

**Issue by lurodrigo** [tidyverse/glue#34]
Glue is not working properly with UTF-8 encoded strings. 

```
> x = "pão"
> x
[1] "pão"
> Encoding(x)
[1] "latin1"
> glue("{x}")
pão
> x = enc2utf8("pão")
> x
[1] "pão"
> Encoding(x)
[1] "UTF-8"
> glue("{x}")
pÃ£o
```

**Comment by krlmlr** [comment]
It would be great if this worked, because we are relying on glue for the error messages in dplyr, which can contain foreign codepoints.
