### ISSUE TITLE
glue of the empty string

### ISSUE THREAD

**Issue by egnha** [tidyverse/glue#35]
Aside from the change in class, `glue()` acts as the identity function on strings without expressions, except the empty string: `glue("")` gives `character(0)`.

Is this exception intended?

**Comment by jimhester** [comment]
No not intended, should be `structure(character(0), class = c("glue", "character"))`

**Comment by egnha** [comment]
Ah, I had overlooked the missing class. Thanks for the fix!

But what I meant to ask is: Is there a good reason why `glue("")` doesn't return `structure("", class = c("glue", "character"))`?, i.e., a reason why the empty string should be treated differently from other strings without expressions?
