### ISSUE TITLE
Formatters

### ISSUE THREAD

**Issue by klmr** [tidyverse/glue#39]
Are there any plans of adding formatters?

To clarify, by “formatter” I mean (1) an interface and (2) a glue syntax that advanced formatting of glue tokens. Here’s an example:

```r
glue('π = {pi}')
glue('π to two decimal places = {format(pi, digits = 3)}')
```

With formatters, the second line could be for instance written as

```r
glue('π to two decimal places = {pi:0.2}')
```

Many libraries offer similar capabilities, for instance [composite formatting in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting).

Ideally this would be extensible, allowing users to register their own formatters. For instance the following is thinkable:

```r
arrgh_glue = function (str, options) {
    gsub('r', 'R', str)
}

# optionally, though ideally not necessary:
#   register_glue_formatter(arrgh = arrgh_glue)

name = 'Konrad'
glue('Hello, {name:arrgh}!')
# Hello, KonRad!
```

[The .NET documentation has some more examples](https://msdn.microsoft.com/en-us/library/system.string.format(v=vs.110).aspx#Format6_Example) that show the scope of what could be possible.

**Comment by jimhester** [comment]
Glue expressions have always been designed to evaluate R code and `pi:0.2` is also a valid R expression. If you want more succinct formatting syntax you can always define a custom function to do so.

**Comment by klmr** [comment]
RIght, the `pi:0.2` syntax probably wouldn’t work in R. I just used it here since that’s the syntax used in e.g. .NET (then again, `:` is pretty much useless in R anyway, so using here would probably do no harm).

As for custom functions: fair enough. But many other string interpolation libraries found it worthwhile to have a dedicated syntax for this.

**Comment by jimhester** [comment]
Once the API for https://github.com/tidyverse/glue/pull/55 is settled, custom formatters will be possible, the PR currently has an example implementation of the `pi:0.2` syntax.

**Comment by klmr** [comment]
Great work! This goes way beyond what I had in mind, which makes it much better since it’s more general.

**Comment by jimhester** [comment]
Closed by https://github.com/tidyverse/glue/commit/d0ced3eb3152132713b69e5b9ac2e8998d48b977, although we can re-open if we later want to include formatters directly in glue itself.
