### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by edarague** [tidyverse/glue#40]
> install.packages("devtools")
trying URL 'https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.4/devtools_1.13.2.zip'
Content type 'application/zip' length 442517 bytes (432 KB)
downloaded 432 KB

package 'devtools' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\edguevara\AppData\Local\Temp\Rtmp4gSnoj\downloaded_packages
> library(tidyverse)
Error: package or namespace load failed for 'tidyverse' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCh
eck = vI[[j]]):
 there is no package called 'glue'
> devtools::install_github("tidyverse/glue")
Downloading GitHub repo tidyverse/glue@master
from URL https://api.github.com/repos/tidyverse/glue/zipball/master
Error: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD
 config CC' had status 1

**Comment by jimhester** [comment]
Just install glue using `install.packages("glue")`.
