### ISSUE TITLE
.envir should accept anything that can be coerced to an environment.

### ISSUE THREAD

**Issue by DarwinAwardWinner** [tidyverse/glue#51]
Sometimes you have the values that you want to interpolate in a list (example: the `params` object in an Rmarkdown file), and you want to interpolate using these values. Currently, you must manually convert this to an environment in order to do so using glue, but it would be nice if the function would do it for you. 

Example:

```R
# using named args
glue("Hello {firstname} {lastname}", firstname="John", lastname="Doe")


person <- c(firstname="John", lastname="Doe")
# Trying to pass a named vector as .envir doesn't workglue("Hello {firstname} {lastname}", .envir=person)
# Must do this instead
glue("Hello {firstname} {lastname}", .envir=as.environment(as.list(person)))
```

The .envir arg should probably satisfy `rlang::is_dictionary` if it isn't an environment.

**Comment by jimhester** [comment]
I think this example would be better served using `glue_data()`.

```r
library(glue)
person <- c(firstname="John", lastname="Doe")
glue_data(as.list(person), "Hello {firstname} {lastname}")
```

**Comment by DarwinAwardWinner** [comment]
Yes, I guess that works pretty well.
