### ISSUE TITLE
Use tidyverse conventions for the website

### ISSUE THREAD

**Issue by hadley** [tidyverse/glue#58]
Ping me once you have the logo and I'll give you the details (which we should write up somewhere)

**Comment by jimhester** [comment]
@hadley So what do we need to change for the website? http://glue.tidyverse.org/

**Comment by hadley** [comment]
I think it now just means using the tidytemplate package?

**Comment by jimhester** [comment]
Ok, that is what I am doing, let me know if you see something wrong that I need to change

https://github.com/tidyverse/glue/blob/db27df0bf5dddae1475d44de1d21c1e36983eee6/_pkgdown.yml#L1-L2

**Comment by hadley** [comment]
I think you need to update tidytemplate so you get correct header.

Also we usually do

```
home:
  strip_header: true
```

**Comment by jimhester** [comment]
Ok looks good now, thanks!
