### ISSUE TITLE
glue_sql adds quotes to tablename 

### ISSUE THREAD

**Issue by RMHogervorst** [tidyverse/glue#69]
I'm guessing this has something to do with my oracle version (11.02.**) but in oracle if you 
quote a tablename it doesn't work.

example:
This is what I want
```
select * from
    scheme1.tablename a,
    scheme2.tablename b
where a.id = b.id
``` 
``` 
tablename <- "scheme1.tablename"
glue_sql(
"
select * from
    {tablename} a,
    scheme2.tablename b
where a.id = b.id
", .con = con)
``` 

results in
```
"
select * from
    `scheme1.tablename` a,
    scheme2.tablename b
where a.id = b.id
"
```

I can use the normal glue, but I hoped that since I give the connection it would pick up the correct behavior

**Comment by jimhester** [comment]
As mentioned in the [details and shown in the examples](http://glue.tidyverse.org/reference/glue_sql.html#details) you need to surround identifiers with backticks. e.g.

```r
glue_sql("
  select * from {`tablename`} a
...
```

**Comment by RMHogervorst** [comment]
thank you for the quick reply Jim!

I was not clear in my example, I did use  backticks in the tablename part. 
```
tablename <- "scheme1.tablename"
glue_sql(
"
select * from
    {`tablename`} a,
    scheme2.tablename b
where a.id = b.id
", .con = con)
```
but the endresult adds quotes to the table name

```
"
select * from
    "scheme1.tablename" a,
    scheme2.tablename b
where a.id = b.id
"
```

**Comment by jimhester** [comment]
The problem here is you are combing the schema and the table (which are two separate identifiers) together into one string. If you really don't want quoting use `DBI::SQL()` when you create the value.
```r
tablename <- DBI::SQL("scheme1.tablename")
```

Or split the table and schema into two separate identifiers
```r
tablename <- "tablename"
schemaname <- "schema1"
glue_sql("
  select * from {`schemaname`}.{`tablename`} a,
...
```

**Comment by RMHogervorst** [comment]
Cool! The database does seem to accept the schema."tablename" syntax.
Man... oracle... 

Thanks for the help!
