### ISSUE TITLE
fcat, fmessage, fwarning, fstop

### ISSUE THREAD

**Issue by hadley** [tidyverse/glue#7]
Set of helpers

**Comment by jimhester** [comment]
How do you think these should handle the additional arguments to the wrapped functions?

```r
fcat <- function(..., .sep = "", .envir = parent.frame(), .file = "", .append = TRUE) {
  cat(f(..., .sep = .sep, .envir = .envir), file = .file, append = .append)
}

# Not sure if appendLF should be `TRUE` or `FALSE`, or if it should be exposed
fmsg <- function(..., .sep = "", .envir = parent.frame(), .domain = NA) {
  message(f(..., .sep = .sep, .envir = .envir), domain = .domain, appendLF = FALSE)
}

# do we want to handle immediate. or different value for noBreaks = FALSE?
fwarn <- function(..., .sep = "", .envir = parent.frame(), .call = FALSE, .domain = NA) {
  warn(f(..., .sep = .sep, .envir = .envir), .call = .call, domain = .domain, noBreaks. = TRUE)
}


fstop <- function(..., .sep = "", .envir = parent.frame(), .call = FALSE, .domain = NA) {
  stop(f(..., .sep = .sep, .envir = .envir), .call = .call, domain = .domain)
}
```

It would also be nice to easily create new condition classes ala (https://github.com/hadley/rlang/blob/849992586ad72c7a79b85c332c39b626e1c1e63d/R/cnd.R#L272-L296), but probably out of scope for this package.

**Comment by hadley** [comment]
Maybe just stick with `fcat()` and `fmessage()` for now? Warning and stopping probably best handled elsewhere

**Comment by jimhester** [comment]
These are fairly easy to do in a package, e.g. https://github.com/r-lib/pkginstall/blob/dedd420187ac3ff1266816db60650355a924f1c1/R/utils.R#L21-L29, so I don't think we need explicit ones here. Can re-open if we decide to down the road.
