### ISSUE TITLE
Trailing newline ignored

### ISSUE THREAD

**Issue by cfhammill** [tidyverse/glue#70]
I'm using glue for some codegen and I noticed it seems to trim a trailing newline.

```
str(glue("\n")) ## empty string
str(glue("\n\n")) ## one newline
```

This may be intentional but I it surprised me at first. Maybe worth documenting.

**Comment by jimhester** [comment]
It is documented in the readme.

https://github.com/tidyverse/glue#leading-whitespace-and-blank-lines-from-the-first-and-last-lines-are-automatically-trimmed

**Comment by jimhester** [comment]
But is not in the function level documentation, I will flesh that out some, thanks!

**Comment by cfhammill** [comment]
Ahh, I missed it, thanks Jim!

**Comment by DSLituiev** [comment]
this is indeed an unexpected feature, took me by surprise. 

When I used it with `cat(glue("abc\n")); cat("d")`  kept getting unexpected results
