### ISSUE TITLE
issue with inserting values into JSON string

### ISSUE THREAD

**Issue by grobins** [tidyverse/glue#72]
I'm trying to perform the following

```
glue('"coordinates": {"longitude": "{midpointLongitude}","latitude": "{midpointLatitude}" },', 
     midpointLongitude = -45.1234,
     midpointLatitude = 173.1234
)
```
but i get the following error 

```
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:35: unexpected ','
1: "longitude": "{midpointLongitude}",
```

Is there something I have to do in order to insert into a JSON template?

**Comment by jimhester** [comment]
All `{` in glue expressions are treated as R code to be evaluated. If you do not want this behavior for a given set of `{` you [need to double them](https://github.com/tidyverse/glue#a-literal-brace-is-inserted-by-using-doubled-braces). If you want to use a different separator which would require less escaping for JSON you can specify [alternative delimiters](https://github.com/tidyverse/glue#alternative-delimiters-can-be-specified-with-open-and-close).

**Comment by grobins** [comment]
Got it, I tried with << and >> as the delimiters and it worked fine. Thanks for the help.
