### ISSUE TITLE
`glue_collapse()` should always return length 1 vectors

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/glue#88]
``` r
length(glue::glue_collapse(character()))
#> [1] 0
length(glue::glue_collapse(""))
#> [1] 1
length(glue::glue_collapse(letters))
#> [1] 1
```

> Created on 2018-04-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Perhaps `glue_collapse()` should always returned a string?

**Comment by jimhester** [comment]
Those are all characters, how is this not type stable?

**Comment by krlmlr** [comment]
The length varies (length 1 vs. length 0), I can't `map_chr(..., glue_collapse)`. Maybe there's a better term for this feature?

**Comment by krlmlr** [comment]
Do we want a type-stable variant, perhaps `glue_collapse1()`?

https://github.com/krlmlr/dm/blob/23b37be9280a227bd21cad8d652a3f6a632ef76a/R/paste.R#L95-L101
