### ISSUE TITLE
Expired certificate for the website

### ISSUE THREAD

**Issue by cderv** [tidyverse/glue#95]
Hi, 

I have this error when I try to go on the website: `SEC_ERROR_EXPIRED_CERTIFICATE`
![image](https://user-images.githubusercontent.com/6791940/41290407-148b494e-6e4d-11e8-93e7-a9b69c064a52.png)
(sorry for french images...)

For translatation, it says that  certificate for https expired June 8th, and that you use HTTP Strict Transport Security so no exception can be made in Firefox

Is this something on my side or really an expired certificate for https ?

**Comment by jimhester** [comment]
This is now fixed, thanks!
