### ISSUE TITLE
Turn off non-ASCII test on CRAN

### ISSUE THREAD

**Issue by jimhester** [tidyverse/glue#99]
https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/glue-00check.html

> running tests for arch 'x64' ... [3s] ERROR
  Running 'testthat.R' [2s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > library(testthat)
  > library(glue)
  > 
  > test_check("glue")
  -- 1. Error: glue always returns UTF-8 encoded strings regardless of input encod
  invalid multibyte character in parser at line 1
  1: withr::with_locale(c(LC_CTYPE = "Chinese (Simplified)_China.936"), {
         z <- "{format(as.Date(\"2018-01-04\"), \"%YÄê\")}"
         z_out <- glue(z)
         expect_equal(Encoding(z_out), "UTF-8")
         expect_equal(z_out, "2018Äê")
     }) at testthat/test-glue.R:296
  2: force(code)
  3: glue(z) at testthat/test-glue.R:298
  4: glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open, .close = .close, 
         .na = .na, .transformer = .transformer)
  5: (function (expr) 
     as.character(.transformer(expr, env)))("format(as.Date(\"2018-01-04\"), \"%Yå¹\xb4\")")
  6: .transformer(expr, env)
  7: eval(parse(text = text, keep.source = FALSE), envir)
  8: parse(text = text, keep.source = FALSE)
>  
>  == testthat results ===========================================================
  OK: 175 SKIPPED: 0 FAILED: 1
>  1. Error: glue always returns UTF-8 encoded strings regardless of input encodings (@test-glue.R#296) 
>  
>  Error: testthat unit tests failed
>  Execution halted

**Comment by stufield** [comment]
Looks like r-devel fixed this
